### ISSUE TITLE
Remove dependency to ``setuptools`` and ``distutil``

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [PyCQA/astroid#1103]
As see in #1030  and #1100 there is a hidden dependency to setuptools (and probably distutils too), we made it explicit in #1100 but the better thing to do would be to remove it entirely if possible.

**Comment by Keuricloud8866** [comment]
How can I learn as begineer

**Comment by Pierre-Sassoulas** [comment]
Hi @Keuricloud8866, what do you want to learn ? In order to fix this ticket you should track the place where setuptools and distutils are used in pylint and find an alternative. For finding alternative we'll probably have to discuss how to do what we were doing before without setuptools.

**Comment by Keuricloud8866** [comment]
I am new and begineer in software IT world i just jumped in and want to be in so

**Comment by Pierre-Sassoulas** [comment]
You should probably check a tutorial about learning programming first. Another useful thing would be to know how to ask question:
- First read the error or documentation
- Second search Google or Stackoverflow
- Third ask for help in the right place

Did you search how to learn programming by yourself first and read a blog about it ? I think you jumped to three and this is not the right place to ask either. This is an issue about a particular issue in a particular software, you were very unlikely to get answers here. (in fact please do not ask other off-topic questions or I'll have to ban you).

**Comment by DanielNoord** [comment]
Closed with #1323

**Comment by DanielNoord** [comment]
Do we still need to dependency on `setuptools` now? It was added in https://github.com/PyCQA/astroid/commit/40629baba2de2c9eb5e11b65798b3fae79f7284a.
Now that we have removed `distutils` I don't think it is necessary, right?

**Comment by Pierre-Sassoulas** [comment]
Probably ? I'm trying to think of a way to test that. Maybe launching pylint test suite in a venv after we deinstalled ``setuptools`` ?
