### ISSUE TITLE
MRO failure on Python 3.7 with typing_extensions

### ISSUE THREAD

**Issue by 9999years** [PyCQA/astroid#1124]
### Steps to reproduce

Run the following script on Python 3.7:

```python
from astroid import parse
module = parse("""
import abc
import typing
import dataclasses

import typing_extensions

T = typing.TypeVar("T")

class MyProtocol(typing_extensions.Protocol): pass
class EarlyBase(typing.Generic[T], MyProtocol): pass
class Base(EarlyBase[T], abc.ABC): pass
class Final(Base[object]): pass
""")

#                    typing.Protocol
#                          |
# typing.Generic[T]    MyProtocol
#              \       /
#              EarlyBase     abc.ABC
#                       \    /
#                        Base
#                         |
#                        Final

final_def = module.body[-1]
final_def.mro()
```

### Current behavior

```
Traceback (most recent call last):
  File "xxx.py", line 31, in <module>
    print("mro:", final_def.mro())
  File "/home/rturner/astroid/astroid/nodes/scoped_nodes.py", line 3009, in mro
    return self._compute_mro(context=context)
  File "/home/rturner/astroid/astroid/nodes/scoped_nodes.py", line 2985, in _compute_mro
    mro = base._compute_mro(context=context)
  File "/home/rturner/astroid/astroid/nodes/scoped_nodes.py", line 2999, in _compute_mro
    return _c3_merge(unmerged_mro, self, context)
  File "/home/rturner/astroid/astroid/nodes/scoped_nodes.py", line 103, in _c3_merge
    context=context,
astroid.exceptions.InconsistentMroError: Cannot create a consistent method resolution order for MROs (tuple, object), (EarlyBase, tuple, Generic, object, MyProtocol), (ABC, object), (tuple, EarlyBase, ABC) of class <ClassDef.Base l.1347 at 0x7fa0efd52590>.
```

### Expected behavior

No MRO error is raised; Python 3.7 doesn't raise an error.

### `python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"` output

2.6.7-dev0; the test case fails in pylint 2.9.6 and on the main branch at commit 6e8699cef0888631bd827b096533fc6e894d2fb2.

**Comment by pagetok** [comment]
Just curious: how did people find out it's the win32 issue without this being mentioned in the original question?

**Comment by Pierre-Sassoulas** [comment]
We have continuous integration for windows/mac/linux if only the windows pipeline fail then it's a windows specific issue :)

**Comment by 9999years** [comment]
Definitely not a Windows exclusive issue. You can see the Linux home directory in the original question!

**Comment by 9999years** [comment]
It also looks like the regression tests you added don't run on 3.7 when the original issue is specific to 3.7?

**Comment by Pierre-Sassoulas** [comment]
> Definitely not a Windows exclusive issue.

Yeah I don't think it's a windows specific issue either, just answering the hypothetical question.  Now that I'm not on mobile anymore windows required a specific treatment in the test, which might have led @pagetok to think that.

https://github.com/pylint-dev/astroid/pull/1364/files#diff-12f4364f9842da707e8418b6ff1172eb8da7c78c3861942e8ec19de16ba24381R1708-R1711

> It also looks like the regression tests you added don't run on 3.7 when the original issue is specific to 3.7?

``@test_utils.require_version(minver="3.7")`` means that the test is running on 3.7, 3.8, 3.10, 3.11, (...). We do not support 3.7 anymore, so we might remove the regr test. Probably not worth the risk if I miss something here.

**Comment by pagetok** [comment]
was there a PR that actually solve this issue? looks like the
currently attached one only deals with Windows and may not be the cause
here.
