### ISSUE TITLE
Regression with dataclass inference

### ISSUE THREAD

**Issue by cdce8p** [PyCQA/astroid#1129]
### Steps to reproduce

```py
from dataclasses import dataclass
from typing import Any, Callable

@dataclass
class A:
    enabled: Callable[[Any], bool]

instance = A(lambda x: x == 42)
instance.enabled(2)  # not-callable
```

### Current behavior

```
************* Module test
test.py:9:0: E1102: instance.enabled is not callable (not-callable)
```

### Expected behavior

No error

### Additional information

Tested with astroid `v2.7.0`.
The issue seems to be a direct result of #1126

/CC: @david-yz-liu @Pierre-Sassoulas

**Comment by david-yz-liu** [comment]
@cdce8p thanks for pointing this out. I'm on it, hope to get up a PR soon.
