### ISSUE TITLE
Inference error with future `__annotations__` on Python 3.7

### ISSUE THREAD

**Issue by mristin** [PyCQA/astroid#1134]
Hi astroid team,
We observed a failure on the following code when we tried to do the inference using astroid 2.7.1 and Python 3.7.9. The code works with Python 3.8.5 without problems.

```python
from __future__ import annotations

import textwrap

import astroid


class Visitor:
    def visit(self, node: astroid.node_classes.NodeNG):
        func_name = "visit_" + node.__class__.__name__
        func = getattr(self, func_name, self.visit_generic)
        return func(node)

    def visit_FunctionDef(
            self,
            node: astroid.nodes.FunctionDef
    ) -> None:
        if node.decorators is None:
            return

        if node.returns is not None:
            try:
                inferred_returns = next(node.returns.infer())

                if isinstance(inferred_returns, astroid.nodes.Const):
                    if inferred_returns.value is None:
                        func_has_result = False

            except astroid.exceptions.NameInferenceError:
                # Ignore uninferrable returns
                pass

    def visit_generic(self, node: astroid.NodeNG) -> None:
        """Propagate the visit to the children."""
        for child in node.get_children():
            self.visit(child)


def main() -> None:
    text = textwrap.dedent('''\
        from __future__ import annotations

        class A:
            @property
            def b(self) -> list[int]:
                return []
        ''')

    tree = astroid.parse(code=text, module_name="somemodule", path="<from code>")

    visitor = Visitor()
    visitor.visit(node=tree)


if __name__ == "__main__":
    main()
```

Here is the full traceback
```
Traceback (most recent call last):
  File "c:\astroid\venv\lib\site-packages\astroid\nodes\scoped_nodes.py", line 2684, in getitem
    methods = lookup(self, "__getitem__")
  File "c:\astroid\venv\lib\site-packages\astroid\interpreter\dunder_lookup.py", line 50, in lookup
    return _class_lookup(node, name)
  File "c:\astroid\venv\lib\site-packages\astroid\interpreter\dunder_lookup.py", line 58, in _class_lookup
    raise AttributeInferenceError(attribute=name, target=node)
astroid.exceptions.AttributeInferenceError: '__getitem__' not found on <ClassDef.list l.0 at 0x1bd258f74c8>.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\astroid\venv\lib\site-packages\astroid\inference.py", line 401, in infer_subscript
    assigned = value.getitem(index_value, context)
  File "c:\astroid\venv\lib\site-packages\astroid\nodes\scoped_nodes.py", line 2697, in getitem
    raise AstroidTypeError(node=self, context=context) from exc
astroid.exceptions.AstroidTypeError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\astroid\problematic.py", line 62, in <module>
    main()
  File "c:\astroid\problematic.py", line 58, in main
    visitor.visit(node=tree)
  File "c:\astroid\problematic.py", line 18, in visit
    return func(node)
  File "c:\astroid\problematic.py", line 42, in visit_generic
    self.visit(child)
  File "c:\astroid\problematic.py", line 18, in visit
    return func(node)
  File "c:\astroid\problematic.py", line 42, in visit_generic
    self.visit(child)
  File "c:\astroid\problematic.py", line 18, in visit
    return func(node)
  File "c:\astroid\problematic.py", line 29, in visit_FunctionDef
    inferred_returns = next(node.returns.infer())
  File "c:\astroid\venv\lib\site-packages\astroid\nodes\node_ng.py", line 98, in infer
    yield from self._infer(context, **kwargs)
  File "c:\astroid\venv\lib\site-packages\astroid\decorators.py", line 136, in raise_if_nothing_inferred
    yield next(generator)
  File "c:\astroid\venv\lib\site-packages\astroid\decorators.py", line 100, in wrapped
    res = next(generator)
  File "c:\astroid\venv\lib\site-packages\astroid\inference.py", line 408, in infer_subscript
    raise InferenceError(node=self, context=context) from exc
astroid.exceptions.InferenceError: Inference failed for <Subscript l.5 at 0x1bd25d27788>.
```

The issue has been originally reported in pyicontract-lint: https://github.com/Parquery/pyicontract-lint/issues/44

Please let me know if you need further detail or if the example posted here is not minimal enough.

Thank you very much for your help in advance!

**Comment by cdce8p** [comment]
I think the issue here is a misunderstanding rather than a bug. Am I correct in assuming the intend here was to infer the function return values?
```py
    def visit_FunctionDef(...):
        ...
        if node.returns is not None:
            try:
                inferred_returns = next(node.returns.infer())
```

If that's the case, you probably want to use `node.infer_call_result` instead. Keep in mind that it can yield more than one item.

In contrast `node.returns` contains the return type annotation which will always be a `<Subscript>` node for `list[int]`. The inference of it will fail for Python 3.7 and 3.8 as `__class_getitem__` was added to `list` in 3.9. (Tested with `3.7.9` and `3.8.10`)

https://docs.python.org/3.10/library/ast.html#ast.FunctionDef

**Comment by mristin** [comment]
Hi @Pierre-Sassoulas,
Thank you very much for your help! I re-implemented the relevant snippet and now it seems to pass on my side on Python 3.7 as well as on Python 3.8. Here's the minimal example:

```python
from __future__ import annotations

import textwrap

import astroid


class Visitor:
    def visit(self, node: astroid.NodeNG):
        func_name = "visit_" + node.__class__.__name__
        func = getattr(self, func_name, self.visit_generic)
        return func(node)

    def visit_FunctionDef(
            self,
            node: astroid.nodes.FunctionDef
    ) -> None:
        if node.decorators is None:
            return

        try:
            inferred_result = node.infer_call_result()

            has_none = False
            result_count = 0
            for result_node in inferred_result:
                print(f"result_node is {result_node!r}")
                result_count += 1

                if (
                        isinstance(result_node, astroid.nodes.Const)
                        and result_node.value is None
                ):
                    has_none = True

            if has_none and result_count == 1:
                func_has_result = False
        except astroid.exceptions.NameInferenceError:
            # Ignore uninferrable returns
            pass

    def visit_generic(self, node: astroid.NodeNG) -> None:
        """Propagate the visit to the children."""
        for child in node.get_children():
            self.visit(child)


def main() -> None:
    text = textwrap.dedent('''\
        from __future__ import annotations

        class A:
            @property
            def a(self) -> list[int]:
                return []
            
            @property    
            def b(self) -> None:
                return None
        ''')

    tree = astroid.parse(code=text, module_name="somemodule", path="<from code>")

    visitor = Visitor()
    visitor.visit(node=tree)


if __name__ == "__main__":
    main()
```

The script outputs:
```
result_node is <List.list l.6 at 0x1d30c4e7bc8>
result_node is <Const.NoneType l.10 at 0x1d30c4e7e08>
```

(`List.list` for the first function and `None` for the second one, as expected.)

Could you please have a look at the changed code? Is it expected that it now works whereas it failed before? Is it because the line `inferred_returns = next(node.returns.infer())` in the previous implementation calls `__class_getitem__` on `list` while `node.infer_call_result()` does not?

**Comment by Pierre-Sassoulas** [comment]
Hi, sorry @mristin I don't think I understand well. Did you make some change in astroid ? If that's the case it's easier to understand if you open a pull request with the modified code and a test that shows what failed before. It's hard to tell what changed by reading the code in the issue :)

**Comment by cdce8p** [comment]
@mristin I assume you meant me here :)

> Could you please have a look at the changed code? Is it expected that this code now works on Python 3.7 whereas the previous code failed?

Yes, that is as expected. Since you would like to infer the results of the function you need to use `infer_call_result()` like you've done here. `node.returns.infer()` would only try to infer the return **type annotation**. Try parsing the following, maybe that will make it a bit clearer:
```py
from __future__ import annotations

class A:
    @property
    def a(self) -> list[int]:
        if some_unknown_function():
            return "Hello World"
        else:
            return None
```

(The type annotations is wrong, but that's just for demonstration purposes.)
In this example the return type for `a` is: `list[int]`. The results, in contrast, are `"Hello World"` and `None` depending on the result of `some_unknown_function`.

> Is it because the line `inferred_returns = next(node.returns.infer())` in the previous implementation calls `__class_getitem__` on `list` while `node.infer_call_result()` does not?

`node.returns.infer()` tries to infer `list[str]` without knowing that it's stringified by `from __future__ import annotations`.

**Comment by mristin** [comment]
@Pierre-Sassoulas please apologize, I indeed meant @cdce8p, but I was too hasty with GitHub's autocomplete :-).

@cdce8p thanks, that clears it up! Btw., can't I just use `node.returns.value` to check that the return annotation is `None`?

**Comment by cdce8p** [comment]
> Btw., can't I just use `node.returns.value` to check that the return annotation is `None`? This would have the benefit that the code would run both on Python 3.7 and later versions. Am I correct to assume that `node.returns.value` does no fancy inference, but returns the annotation as-is?

I fear it's not as easy as you think it will be. True, `node.returns` will contain the annotation node as-is. However, there are multiple issues you should be aware of. First, probably the easiest one to solve, the type annotation node can be almost any node that inherits from `NodeNG`, not all of them have a `value` attribute. Second, you will also have to consider union types. And third, what about type aliases? There you would need inference again which as we determined earlier can result in errors that need to be dealt with.

Just my personal opinion, I would continue with `infer_call_result()` if that's enough for your use case. Astroid isn't (yet?) equipped to properly work with type annotations.

**Comment by mristin** [comment]
P.S. @cdce8p the snippet for checking for `None` result in my previous message would look something like:
```python
if node.returns is not None:
    func_has_result = not (
        isinstance(node.returns, astroid.Const) 
        and node.returns.value is None
    )
```

**Comment by mristin** [comment]
@cdce8p sorry for intertwined posting -- I've just realized you already answered, while I was writing my P.S.

In my use case, I really need to check only that the developer explicitly marked the function to return `None`. While I'd miss cases where type aliases are used, those must be pretty rare -- who on Earth would ever alias `None` :-).

I'll close the issue as we resolved my doubts. Please re-open if you need further information from my side. Thanks a lot for your help and very informative clarifications!
