### ISSUE TITLE
License in pypi includes LGPLv2

### ISSUE THREAD

**Issue by VincentKetelaars** [PyCQA/astroid#1159]
### Steps to reproduce

1. Visit https://pypi.org/project/astroid/
2. Check License on the right. It states: License: GNU Lesser General Public License v2 (LGPLv2) (LGPL-2.1-or-later)

### Current behavior

The License includes LGPLv2

### Expected behavior

The License ought to be only LGPL-2.1-or-later as stated in `LICENSE` as well as the `setup.cfg` files

**Comment by Pierre-Sassoulas** [comment]
Where do you think the information displayed in pypi comes if not from the setup.cfg ?

**Comment by VincentKetelaars** [comment]
> Where do you think the information displayed in pypi comes if not from the setup.cfg ?

I do not know, otherwise I would have included it :) I was hoping someone here might be more knowledgeable.

**Comment by Pierre-Sassoulas** [comment]
The information is displayed this way by pypi there's nothing we can do.
