### ISSUE TITLE
Provide generator for classes

### ISSUE THREAD

**Issue by elfring** [PyCQA/astroid#1227]
[Nodes are offered by this programming interface](https://docs.python.org/3/library/ast.html#ast.NodeVisitor "Visiting nodes").
They should also be provided for further data processing by [the means of a generator](https://docs.python.org/3/glossary.html#term-generator "Documentation").
The relevant items should be restricted to classes.

**Comment by Pierre-Sassoulas** [comment]
See https://github.com/PyCQA/astroid/issues/1229#issuecomment-955017032
