### ISSUE TITLE
Please update the typed-ast version

### ISSUE THREAD

**Issue by srittau** [PyCQA/astroid#1237]
Please update the dependency on typed-ast in `setup.cfg` to `typed-ast>=1.4.0,<2`. typed-ast 1.5 contains a critical fix for Python 3.9, which causes incompatibilities with packages that still rely on typed-ast on Python >= 3.8. See for example google/pytype#1047. typed-ast is supposed to remain API compatible during 1.x. (And it's unlikely there ever will be a version 2.)

**Comment by Pierre-Sassoulas** [comment]
Thank you for opening the issue, we'll release that in 2.8.5 soon.

**Comment by srittau** [comment]
Thanks!

**Comment by Pierre-Sassoulas** [comment]
We released astroid 2.8.5, this should fix the issue.
