### ISSUE TITLE
TypeError: Plain typing.NoReturn is not valid as type argument in Astroid 2.8.5 + Python 3.7.0/1

### ISSUE THREAD

**Issue by drasmuss** [PyCQA/astroid#1239]
### Steps to reproduce

1. Use Python 3.7.0 or 3.7.1
2. pip install astroid==2.8.5
3. python -c "import astroid"

### Current behavior

An error is raised
```
TypeError: Plain typing.NoReturn is not valid as type argument
```

In this commit https://github.com/PyCQA/astroid/commit/b62f243b16b7f435c8be869577959e95a7927a91#diff-039e09546480e9ce70fc9a23e975f1ac2364f6d0192e330311d204653947a216R34 there is a conditional import that checks if Python >= 3.6.2, but that should also include Python 3.7.0 and 3.7.1 (which have the same issue as Python 3.6.0/1).

### Expected behavior

There should be no error

### python -c "from astroid import __pkginfo__; print(__pkginfo__.version)" output

This raises the same error as above

**Comment by DanielNoord** [comment]
This seems to be caused by https://bugs.python.org/issue34921

Perhaps we also need to update the import guards in `pylint`?

**Comment by Pierre-Sassoulas** [comment]
I was in the process of adding ``flake8-typing-import`` to the pre-commit hooks but it seems it's not yet detected.
