### ISSUE TITLE
deque.insert() has reversed args

### ISSUE THREAD

**Issue by belm0** [PyCQA/astroid#1260]
### Steps to reproduce

https://docs.python.org/3/library/collections.html#collections.deque.insert

```python
class MyDeque(collections.deque):
    def insert(i, x): pass
```

### Current behavior
pylint says:
```
W0237: Parameter 'x' has been renamed to 'i' in overridden 'MyDeque.insert' method (arguments-renamed)
W0237: Parameter 'i' has been renamed to 'x' in overridden 'MyDeque.insert' method (arguments-renamed)
```
### Expected behavior
no error

### Version
2.8.4

**Comment by cdce8p** [comment]
This looks like a bug. I saw that you already fixed it in your fork. Would you mind opening a PR for it? I don't think that we need a test case for it so the change itself with a short changelog entry should be enough.

**Comment by belm0** [comment]
oops, I'll make a PR-- thought I had done so

**Comment by belm0** [comment]
(rebasing to main and correcting changelog shortly)
