### ISSUE TITLE
``nodes.Module`` don't have a ``end_lineno`` and ``end_col_offset``

### ISSUE THREAD

**Issue by DanielNoord** [PyCQA/astroid#1273]
### Steps to reproduce

```python
import astroid

code = """
    print("a module")
    """

module = astroid.parse(code)
print(module.end_lineno)
print(module.end_col_offset)
```

### Current behavior

`AttributeError` on both of the last lines.

### Expected behavior

@cdce8p Let me know if I misunderstood you, but I thought we wanted these to be accessible on all nodes, just initialised as `None`.
If that was not the case, I would make the case to do so as it allows you to do `node.end_lineno` without running in to `AttributeError`'s.

### Version

Latest `main`.

**Comment by cdce8p** [comment]
> but I thought we wanted these to be accessible on all nodes, just initialised as None.

Yeah, that was the idea initially.

> `AttributeError` on both of the last lines.

For now a workaround would be to use `hasattr(node, "end_lineno")`. Not pretty but it should do. That should unblock https://github.com/PyCQA/pylint/pull/5343.

--
We could try to address it  in #1262. The issue are these lines here
https://github.com/PyCQA/astroid/blob/775c8f7acb97e50cd643b6e1a20042aa8cfa98a3/astroid/nodes/scoped_nodes.py#L472-L475
combined with the missing `super().__init__()` call.
I noticed just now that the `lineno` for `Module` is set to `0`. The type annotation thus doesn't make sense.
https://github.com/PyCQA/astroid/blob/775c8f7acb97e50cd643b6e1a20042aa8cfa98a3/astroid/nodes/scoped_nodes.py#L387-L396

There could also be an argument that it should be `lineno = 1` instead. As all are `1-indexed`.
