### ISSUE TITLE
as_string.py problems

### ISSUE THREAD

**Issue by WenJinfeng** [PyCQA/astroid#1281]
When I used the astroid package to transfer the corresponding source code, the conversion of some nodes contained in as_string.py may be problematic. Problematic methods are mainly about visit_assign, visit_classdef, _docs_dedent, visit_return, visit_boolop and so on. Thanks! Please modify them.

Code modification can be refereed in #1280
For my solutions, some may not work in certain situations.

**Comment by cdce8p** [comment]
Closing this one. Without any concrete examples (of problems) it's difficult for us to evaluate any required changes.
