### ISSUE TITLE
Is `max_inferred = 100` too low?

### ISSUE THREAD

**Issue by anders-kiaer** [PyCQA/astroid#1309]
### Steps to reproduce

See https://github.com/PyCQA/pylint/issues/4577#issuecomment-1000245962.

### Current behavior

False positives in `pylint` unless `max_inferred` on this line is set to a higher value:
https://github.com/PyCQA/astroid/blob/7d3b41ceee93f75fbd6bb0da8e803c713319a6ed/astroid/context.py#L48

### Expected behavior

No false positives based on `max_inferred` value.

### Additional context

I don't know `astroid`/`pylint` code base enough to know if setting `max_inferred` to higher value only removes the `pandas` symptons seen in https://github.com/PyCQA/pylint/issues/4577, or if it is a decent fix (I guess there is a risk for the former to be true?)

**Comment by brycepg** [comment]
I think this would exacerbate performance issues. Esp with https://github.com/PyCQA/pylint/issues/5835 for pandas
