### ISSUE TITLE
celery + pylint ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==

### ISSUE THREAD

**Issue by GabLeRoux** [PyCQA/astroid#1329]
I recently ugraded `celery` in one of my projects due to a recent vulnerability. I use `pip-tools` to only define what I use so I can easily know what requirements are dependencies of dependencies. I also have `astroid` as a `pylint` dependency.

When running the following command in my pipelines:
```bash
pip install -r requirements.txt --upgrade
```

I get the following error:

```
[...]
Collecting setuptools>=20.0
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    setuptools>=20.0 from https://files.pythonhosted.org/packages/b0/3a/88b210db68e56854d0bcf4b38e165e03be377e13907746f825790f3df5bf/setuptools-59.6.0-py3-none-any.whl#sha256=4ce92f1e1f8f01233ee9952c04f6b81d1e02939d6e1b488428154974a4d0783e (from astroid==2.8.6->-r requirements.txt (line 47))
```

Related lines I have in `requirements.txt`:

```
astroid==2.8.6 \
    --hash=sha256:5f6f75e45f15290e73b56f9dfde95b4bf96382284cde406ef4203e928335a495 \
    --hash=sha256:cd8326b424c971e7d87678609cf6275d22028afd37d6ac59c16d47f1245882f6
    # via
    #   pylint
    #   pylint-celery
```

I think removing `setuptools` as suggested in related #1103 might solve this issue in the future :sweat_smile: .

## How to reproduce

`requirements-fail.in`:
```
celery==5.2.3
pylint==2.11.1
pylint-django==2.4.4
pylint-celery==0.3
```

`requirements-pass.in`:
```
celery==5.2.2
pylint==2.11.1
pylint-django==2.4.4
pylint-celery==0.3
```

```Dockerfile
FROM python:3.9.7

RUN pip install --upgrade pip && pip install pip-tools
```

```bash
docker build . -t astroid-setuptools-issue

# example failing
docker run --rm -v "$(pwd)":/app -w /app astroid-setuptools-issue \
  pip-compile --generate-hashes -o requirements.txt requirements-fail.in
docker run --rm -v "$(pwd)":/app -w /app astroid-setuptools-issue \
  pip install -r requirements.txt

# example succeeding
docker run --rm -v "$(pwd)":/app -w /app astroid-setuptools-issue \
  pip-compile --generate-hashes -o requirements.txt requirements-pass.in
docker run --rm -v "$(pwd)":/app -w /app astroid-setuptools-issue \
  pip install -r requirements.txt
```

Here's a related discussion I created on Celery project:  
https://github.com/celery/celery/discussions/7202

**Comment by Pierre-Sassoulas** [comment]
astroid can't pin dependencies, especially setuptools. That would very quickly create impossible to solve conflict in the package using astroid as a dependency. If you want a pinned build you need to pin the dependencies yourself. See https://github.com/PyCQA/pylint/issues/5485 for a more verbose explanation.
