### ISSUE TITLE
`brain_attrs.py` does not support attrs v21.3.0+

### ISSUE THREAD

**Issue by jacobbogdanov** [PyCQA/astroid#1330]
### Steps to reproduce

The [latest release](https://github.com/python-attrs/attrs/releases/tag/21.3.0) of attrs added a new module `attrs` and it seems that pylint does not recognize it.

```py
from typing import List

import attr
import attrs  # new in 21.3.0


@attr.define
class Old:
    items: List[str] = attr.field(factory=list)


@attrs.define
class New:
    items: List[str] = attrs.field(factory=list)


old = Old(["one", "two"])
assert old.items[0] == "one"  # no error here

new = New(["three", "four"])
assert new.items[0] == "three"  # E1136: Value 'new.items' is unsubscriptable (unsubscriptable-object)
```

Running `pylint` on this file causes an `unsubscriptable-object` error for only the `New` class.

### Current behavior
`unsubscriptable-object` for `attrs.field` but NOT `attr.field`

### Expected behavior

`attrs.field` (and friends) should be treated like `attr.field`

### `python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"` output
2.9.2

Below is also the version of pylint used to reproduce the error above.
```py
> pylint --version
pylint 2.12.2
astroid 2.9.2
Python 3.6.12 (default, Dec  2 2020, 12:31:12) 
[GCC Apple LLVM 12.0.0 (clang-1200.0.32.27)]
```

**Comment by DanielNoord** [comment]
This should be relatively easy to fix by adding some values in:
https://github.com/PyCQA/astroid/blob/d2a5b3c7b1e203fec3c7ca73c30eb1785d3d4d0a/astroid/brain/brain_attrs.py#L13-L14

However, I have never used `attrs` so I have no idea of the new `attrs` has the same `NAMES` as `attr`. I think we would all very much welcome a PR from somebody that has used the package themselves and knows whether they are indeed the same.

**Comment by Pierre-Sassoulas** [comment]
Need to add a changelog entry before release, thanks @DanielNoord for noticing :)
