### ISSUE TITLE
Implementation question

### ISSUE THREAD

**Issue by tristanlatr** [PyCQA/astroid#1336]
In the [documentation](https://pylint.pycqa.org/projects/astroid/en/latest/api/general.html) it's written "Methods are added by monkey patching ast classes.", referring to new methods of the `NodeNG` and other subclasses. 

Is this still the case?

**Comment by DanielNoord** [comment]
I believe this is no longer the case as we're creating new classes and as you identified don't strictly following attribute names as defined by `ast`. Would you be willing to open a PR that fixes this sentence in the documentation?

**Comment by Pierre-Sassoulas** [comment]
[This comment](https://github.com/PyCQA/astroid/pull/1218#issuecomment-959033531) seems to be related to the issue in a MR that was aiming as removing inconsistencies between some classes and the AST.

>  the ast changes with every Python release. These inconsistencies are a direct result of that. We can easily add new arguments to postinit whereas with __init__ we would create breaking changes or change the order, i.e. parent isn't the last anymore. One of the major things astroid does so well, is hide the ast behind a somewhat stable interface pylint and plugins can work with. As for the need to "retro-engineer" classes, I would be surprised if anyone is able to write plugins without at least looking at the documentation, sometimes even that isn't enough.
