### ISSUE TITLE
Impossible to get correct line number for the docstrings

### ISSUE THREAD

**Issue by tristanlatr** [PyCQA/astroid#1340]
# Current behavior: 

Removing the first `ast.Expr` from the tree to populate `.doc` property makes it impossible to get correct line number for the docstirng. 

We ca start a module docstring at the line 3:

```
#!/usr/bin/env python3

"""module docstring"""
...
```

Maybe there is a workaround that I did find, but it looks like the constant node information is lost. 

The core of the issue lies down in the `TreeRebuilder._get_doc()` method. 

https://github.com/PyCQA/astroid/blob/82bf77d54393a52ecd07d50a791f5e1a63369f11/astroid/rebuilder.py#L122

# Expected behavior: 

The expected behaviour, in my opinion is not to remove the `Expr` node from the container such that users can use correct line numbers and report docstring warnings with better accuracy. 

Astroid version: 2.9.3

**Comment by DanielNoord** [comment]
#1276 is actually working on this, but we ran into issues with the different `ast` parsers on different versions and implementations of Python.

Note that the line numbers are not correct on some versions which is why the PR stalled a bit.

**Comment by Pierre-Sassoulas** [comment]
Are you on a version lower than python 3.8 @tristanlatr ?

**Comment by tristanlatr** [comment]
I'm trying to write code that is python 3.6+ compatible.

**Comment by Pierre-Sassoulas** [comment]
OK, to summarize python 3.8 has better lineno/column and we're focusing on python 3.8+ because fixing the information coming from the ast takes a long time. Also python 3.6+ is EOL now. That said I've seen [this comment](https://github.com/PyCQA/astroid/pull/1276#discussion_r783337011) you made and if it works we could merge.

**Comment by tristanlatr** [comment]
Until #1276 is merged, my workaround is the following:

```python
astroid.rebuilder.TreeRebuilder._get_doc = lambda _,o:(o, None)
```

Then parse docstrings statements manually.
