### ISSUE TITLE
Provide base `NodeVisitor` class

### ISSUE THREAD

**Issue by tristanlatr** [PyCQA/astroid#1342]
### Current behavior

The is no equivalent for `ast.NodeVisitor` and the `ast.NodeVisitor` class simply does not work with astroid classes (it relies on the `_fields` class varaible, which is named `_astroid_fields` in astroid). 

### Expected behavior

Provide a base visitor to walk an astroid tree.

Document the fact that visitor methods are lower case by convention. 

astroid version: 2.9.3

**Comment by cdce8p** [comment]
See https://github.com/PyCQA/astroid/pull/1348#issuecomment-1052742282
At the current moment, this is not something I would like to add to astroid.
