### ISSUE TITLE
AstroidBuilder.add_from_names_to_locals() should use Module.wildcard_import_names(), not Module.public_names()

### ISSUE THREAD

**Issue by tristanlatr** [PyCQA/astroid#1362]
### Current behavior

It looks like `AstroidBuilder.add_from_names_to_locals()` is only looking at the `Module.public_names()` methods where it should use `Module.wildcard_import_names()` instead, I think. 

It will miss names  in `__all__` variables. 

### Reproducer
```python
def test_astroid_wildcard() -> None:
    builder = astroid.builder.AstroidBuilder()
        mod = builder.string_build("""\
    __all__=['_f']
    class _f:
        pass
    """, modname='mod')
        mod2 = builder.string_build("""\
    from mod import *
    i = _f()
    """, modname='mod2')
    
    assert mod2.locals.get('_f') is not None
E       AssertionError: assert None is not None
```

astroid version 2.9.3

**Comment by cdce8p** [comment]
Not sure about that. Why would you want to include private names in `__all__`? By definition `__all__` should be the public interface, these names could be used in another module.

**Comment by tristanlatr** [comment]
This is how the python wildcard import mechanism works, though. 

`astroid` behaviour is currently incorrect.

**Comment by cdce8p** [comment]
> `astroid` behaviour is currently incorrect.

Only technically. With a legacy codebase like astroid there is usually a good reason why it was done that way. Especially when it was last changed 5 years ago. Looking a bit deeper, it actually started out with `wildcard_import_names()` but was changed to `public_names()` in https://github.com/rogalski/astroid/commit/82c6ef644a2efb77217a23d9b8a6cfb5caffb4ba. The former added too many false positives.

**Comment by tristanlatr** [comment]
Ok I get it. 

What about the following: 
 - If `__all__` variable is a tuple, then use that values.
 - Else use `public_names()`.

Then, we can look at inferring list values for `__all__` in later step, or never. 
But at least, have support for __all__ as tuple (if there is a single assignment), which is the best practice, would be good. And it won't introduce false positive (since tuple is an immutable type, we're sure we have the correct information). 

Tell me what you think.

**Comment by cdce8p** [comment]
It might be immutable, but you're still able to assign another value to it. It doesn't make sense to change something that works. Think of working on astroid like walking on eggs. It's much more likely that you break something, than not.

Nearly every change is destined to produce a new regression. Just because of the complexity we deal we here. Maybe that helps understand why I'm so reluctant to adding changing existing or adding new features.

**Comment by tristanlatr** [comment]
> but you're still able to assign another value to it

This is why talked about checking if the tuple has a single assignment. Of course I’m talking about literal tuples, not created dynamically.

You know the saying « we don’t do omelette without breaking eggs » ? 

What I mean is, since astroid is not used to control nuclear missiles launching, it’s ok to add new features and improvements that could potentially create false positives. Then false positives will be reported and devepment can continue.

In my opinion, refusing new features just because it **might** break something is not a valid argument. Again, we are not developing a tool that peoples lifes depends on, so we have some flexibility.

talk to you later

**Comment by cdce8p** [comment]
> This is why talked about checking if the tuple has a single assignment. Of course I’m talking about literal tuples, not created dynamically.

Good luck getting it right every time.

> What I mean is, since astroid is not used to control nuclear missiles launching, it’s ok to add new features and improvements that could potentially create false positives. Then false positives will be reported and devepment can continue.

> In my opinion, refusing new features just because it **might** break something is not a valid argument.

I've only said I'm hesitant. The issue here is that it's just not worth the time.
I for one am against this change.
