### ISSUE TITLE
`inference_tip` suppresses transformation of built-in `property`

### ISSUE THREAD

**Issue by areveny** [PyCQA/astroid#1365]
### Steps to reproduce

1. Run Astroid on a file with a call to `property`
2. The replacement/transformation does not seem to occur. I've tried putting a breakpoint in `brain_builtin_inference.infer_property` but it never gets hit.

```
class Something:
    def getter():
        return 5
    asd = property(getter)
```

### Current behavior
This follows from a flaky error we were seeing on https://github.com/PyCQA/pylint/pull/5610 where we would semi-randomly get a `Property` node without `args`.

In `brain_builtin_inference.py`, all the transforms are wrapped in `inference_tip`. `inference_tip` does not replace `node` with the outcome of the `transform` function, it just stores an inference in `node._explicit_inference`. There is a `@wrapt.decorator` annotation on`inference_tip_cached` that seems important for grasping this issue but I don't understand it well enough yet.

The returned node from `inference_tip.inference_tip.transform` replaces the original in `transforms._transform`, but we return the original node so there is no replacement.
 
### Expected behavior
The function call to the builtin `property` should be replaced with an `objects.Property` node.

The flaky test in the linked Pylint issue suggests that sometimes we do transform into `Property` but I can't figure out what triggers those cases. Possibly something to do with the inference tip cache.

### `python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"` output
2.10.0-dev0

**Comment by DanielNoord** [comment]
@areveny What platform are you developing on? For me `infer_property` gets called every time when I run `pylint` over you code example.. I'm on Mac.

**Comment by areveny** [comment]
I'm on Mac M1.

**Comment by DanielNoord** [comment]
```diff
diff --git a/astroid/brain/brain_builtin_inference.py b/astroid/brain/brain_builtin_inference.py
index 0bf352607..3ea683a12 100644
--- a/astroid/brain/brain_builtin_inference.py
+++ b/astroid/brain/brain_builtin_inference.py
@@ -553,6 +553,7 @@ def infer_property(node, context=None):
     This only infers the output of `property`
     call, not the arguments themselves.
     """
+    print("CALLED")
     if len(node.args) < 1:
         # Invalid property call.
         raise UseInferenceDefault
```

```console
❯ cat test.py
class Something:
    def getter():
        return 5

    asd = property(getter)
❯ pylint test.py
CALLED
************* Module test
test.py:2:4: E0211: Method has no argument (no-method-argument)

--------------------------------------------------------------------
Your code has been rated at -2.50/10 (previous run: -2.50/10, +0.00)
```

On my end 😅 Seems pretty consistent as well, in 10x I saw it never not print.

**Comment by areveny** [comment]
Okay, I'm getting that too now with the print statement. I guess it's obfuscated from the debugger.

But there is still the issue of the `property` call not being transformed (except when that test fails). Do we want calls to built-in `property` to be replaced with `objects.Property` or is it just for inference?

**Comment by DanielNoord** [comment]
Are you sure? I think this makes sure the result is actually passed to the correct function:
https://github.com/PyCQA/astroid/blob/e00545978158ced5bacf8fede365efd0d690d320/astroid/brain/brain_builtin_inference.py#L186-L201

Specifically L187

**Comment by areveny** [comment]
Thanks. I'm not 100% here but I should be able to write a test for the `Property.args` issue.
