### ISSUE TITLE
Cannot infer assignment with operator for a simple list of strings

### ISSUE THREAD

**Issue by tristanlatr** [PyCQA/astroid#1398]
### Steps to reproduce

```python
def test_imported_module_var_inferable():
    mod1 = parse(("from top.mod import v as z\n"
                 "w = [1] + z"),
                 module_name='top')
    mod2 = parse("v = [2]", module_name='top.mod')
    w_val = mod1.body[-1].value
    i_w_val = next(w_val.infer())
    assert i_w_val != util.Uninferable
    assert i_w_val.as_string() == "[1, 2]" # Works

def test_imported_module_var_inferable2():
    mod1 = parse(("from top.mod import v as z\n"
                 "w = ['1'] + z"),
                 module_name='top')
    mod2 = parse("v = ['2']", module_name='top.mod')
    w_val = mod1.body[-1].value
    i_w_val = next(w_val.infer())
    assert i_w_val != util.Uninferable
    assert i_w_val.as_string() == "['1', '2']" # Fails with result ['1', 2] instead

def test_imported_module_var_inferable3():
    mod1 = parse(("from top.mod import __dunder_var__ as v\n"
                 "__dunder_var__ = ['w'] + v"),
                 module_name='top')
    mod2 = parse("__dunder_var__ = ['v']", module_name='top.mod')
    w_val = mod1.body[-1].value
    i_w_val = next(w_val.infer())
    assert i_w_val != util.Uninferable # Retuns Uninferable
    assert i_w_val.as_string() == "['w', 'v']"
```

### Current behavior

It seems that operators are fully supported for lists of ints but not for list of strings, I'm unsure why, it seems the same level of complexity. Also it's very weird that it gives the `Uninferable` result for dunder variables. 

### Expected behavior

All tests should pass IMO. 

Astroid version 2.9.3

**Comment by tristanlatr** [comment]
Sorry this might be false manipulation, I've added these tests to tests/unittest_inference.py and they failed, but running them manually in the python interactive interpreter, it works as expected. So I'm confused.

**Comment by Pierre-Sassoulas** [comment]
If you open a PR adding those tests we'll be able to see if they pass for all interpreters or only some of them :)

**Comment by tristanlatr** [comment]
So yes it fails @Pierre-Sassoulas, do you have an idea where to look for the issue? Thanks

**Comment by tristanlatr** [comment]
It's so werid because the follwing works: 

```python
>>> from astroid import parse
>>> mod1 = parse(("from top.mod import __dunder_var__ as v\n"
...                  "__dunder_var__ = ['w'] + v"),
...                  module_name='top')
>>> mod2 = parse("__dunder_var__ = ['v']", module_name='top.mod')
>>> list(mod1.body[-1].value.infer())[0].as_string()
"['w', 'v']"
```

**Comment by Pierre-Sassoulas** [comment]
Could it be because ``from top.mod`` is importable in your local environment ? (I don't know anything about this module so I might be off)

**Comment by tristanlatr** [comment]
No, top.mod is only defined because I passed module_name=“top.mod” to tye parse() function. And it should work right ?

**Comment by tristanlatr** [comment]
Ok, sorry that was indeed a false manipulation, the fake module `top.mod` was already in the AstroidManager cache such that it created some side effects on the inference even if we have parsed another module with the same name after. 

Adding `AstroidManager().clear_cache()` before the tests seems to workaround the problem.
