### ISSUE TITLE
Cannot infer BinOp result if operands share same node

### ISSUE THREAD

**Issue by eugene57** [PyCQA/astroid#1402]
### Steps to reproduce

Run this code:
```python
import astroid

code = """
x = 1
y1 = 2 * x
y2 = x * 3
y3 = y1 * y2
"""

ast = astroid.parse(code)

for name in ('x', 'y1', 'y2', 'y3'):
  node = ast.locals[name][0]
  print(name, node.inferred())
```

### Current behavior
```
x [<Const.int l.2 at 0x7fffe84aef50>]
y1 [<Const.int l.None at 0x7fffe845ec10>]
y2 [<Const.int l.None at 0x7fffe845eb90>]
y3 [Uninferable]
```

Note that `y1` and `y2` are inferred correctly. But when inferring `y3`, there is `x` referenced both by lhs and by rhs.

I quickly debugged `astroid.inference._infer_binop` and only one of `list(lhs_iter)` and `list(rhs_infer)` returns correct result (the one computed first); the second one returns `[Uninferable]`.

### Expected behavior

I would expect `y3` to be inferred as int too.

### `python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"` output
2.4.2

**Comment by DanielNoord** [comment]
I can't reproduce this in on `main`. Note that the version of `astroid` you're using is quite old. Updating will probably resolve this.
