### ISSUE TITLE
dict.copy() result is not inferred as dict

### ISSUE THREAD

**Issue by eugene57** [PyCQA/astroid#1403]
### Steps to reproduce

Run this code:
```python
import astroid

code = """
x = dict()
y = x.copy()
"""

ast = astroid.parse(code)

for name in ('x', 'y'):
  node = ast.locals[name][0]
  print(name, node.inferred())
```

### Current behavior
x [<Dict.dict l.2 at 0x7fffe852e110>]
y [Uninferable]

### Expected behavior
I expect `y` to be inferred as `dict` too.

### `python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"` output
2.4.2

**Comment by timmartin** [comment]
I think the same issue applies to `list`, `set` and `bytearray`. I think we can deal with all these at the same time.
