### ISSUE TITLE
Instance attributes of ancestor classes are not inferred

### ISSUE THREAD

**Issue by eugene57** [PyCQA/astroid#1405]
### Steps to reproduce

Run this code:
```python
import astroid

code = """
class A:
  def __init__(self):
    self.x = 42

class B(A):
  pass

a = A()
a_x = a.x
b = B()
b_x = b.x
"""

ast = astroid.parse(code)

for name in ('a', 'a_x', 'b', 'b_x'):
  node = ast.locals[name][0]
  print(name, node.inferred())
```

### Current behavior
```
a [<Instance of .A at 0x140737057407824>]
a_x [<Const.int l.4 at 0x7fffe6557690>]
b [<Instance of .B at 0x140737057408208>]
b_x [Uninferable]
```

Things start going wrong in `ClassDef.instance_attr_ancestors`. Call to `self.ancestors(context=context)` yields nothing. While call  to `self.ancestors(context=None)` yields `[<ClassDef.A l.2 at 0x7fffce5e3610>, <ClassDef.object l.0 at 0x7fffe91f68d0>]`.

### Expected behavior
I expect `b_x` to be inferred as `int`.

### `python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"` output
2.4.2

**Comment by DanielNoord** [comment]
I can't reproduce this in on ``main``. Note that the version of ``astroid`` you're using is quite old. Updating will probably resolve this.
