### ISSUE TITLE
Rename of branches is incorrect

### ISSUE THREAD

**Issue by DanielNoord** [PyCQA/astroid#1479]
@Pierre-Sassoulas I think you might have done this, but I'm not sure.

Some time ago all branch names have been updated. This also included the `2.0` branch into `maintenance/2.0.x`. However, this was not the `2.0.x` branch but rather a WIP branch for a complete overhaul of `astroid`, which has sadly failed.
See for example this issue https://github.com/PyCQA/astroid/issues/679, which refers to the branch and now links to the incorrectly named branch.

Since I did not do the change I do not know if there are any other branches that have been renamed incorrectly, but I would ask the person who did so to revisit the renaming and see if there are any other issues.

**Comment by Pierre-Sassoulas** [comment]
Yeap, that's me 😄

**Comment by Pierre-Sassoulas** [comment]
Renamed to ``2.0.experimental``

**Comment by Pierre-Sassoulas** [comment]
Yeah maybe all of them but the current one ? I was keeping them because they were there , but I think you're right. (And we really don't want to maintain astroid 2.1)

**Comment by Pierre-Sassoulas** [comment]
I don't know what we should do with the 2.0 experimental branch now.

**Comment by DanielNoord** [comment]
Let's keep it around. There is no tag for it and it is good reference to look into for some open issues + what other solutions to common problems have been thgouht of.
