### ISSUE TITLE
Turn on comments in coveralls

### ISSUE THREAD

**Issue by DanielNoord** [PyCQA/astroid#1482]
Could it be that the coverage comment from coveralls is not turned on? Would be helpful if we could turn it on for the project!

**Comment by DanielNoord** [comment]
@Pierre-Sassoulas Could you turn on the "advanced" or "expanded" version? Or whatever they call it. That way we also get the table with changed files.

**Comment by Pierre-Sassoulas** [comment]
It worked on https://github.com/PyCQA/astroid/pull/1189, I changed to advanced :) I tried to forbid coverage decrease of more than 0.05% too.
