### ISSUE TITLE
Test issue with 3.11

### ISSUE THREAD

**Issue by cdce8p** [PyCQA/astroid#1551]
Managed to track down the test issue we are seeing with `3.11.0b1` a bit. Seems like it's partially caused by another test case which is why I wasn't able to reproduce it locally at first. The following command can be used to recreate the issue

```
pytest \
    tests/unittest_brain.py::ModuleExtenderTest::test_extension_modules \
    tests/unittest_object_model.py::ExceptionModelTest::test_valueerror_py3
```

In particular it seems like the `unittest` module extender is partially responsible. Not sure though if it's a false positive or a real issue.
https://github.com/PyCQA/astroid/blob/0bf711f84d2de55bf777b45cec2449ce776a669a/astroid/brain/brain_unittest.py#L28-L31

So far I haven't figured out what exactly is going on here. It must have been a change in `3.11.0b1` though since `3.11.0a7` was ok. Maybe you two have an idea @DanielNoord @jacobtylerwalls?

/CC: @Pierre-Sassoulas

https://docs.python.org/3.11/whatsnew/changelog.html#python-3-11-0-beta-1

**Comment by DanielNoord** [comment]
Haven't looked at this myself, but one user also reports this on the latest 3.8:

https://github.com/PyCQA/astroid/commit/78a486dc7ecc2567b85ba9d4a85e20639ed71aad#commitcomment-73321532

Not sure if that is the same bug or if it is actually valid, but that might help narrow this down?

**Comment by jacobtylerwalls** [comment]
see https://github.com/python/cpython/pull/28045

**Comment by cdce8p** [comment]
> see [python/cpython#28045](https://github.com/python/cpython/pull/28045)

That looked promising. However, I did bisect it to https://github.com/python/cpython/pull/92202
Need to take a closer look tomorrow.
