### ISSUE TITLE
`_ast.Attribute` objects in a module are assigned the same `attr` values

### ISSUE THREAD

**Issue by gurukamath** [PyCQA/astroid#1620]
### Steps to reproduce

1. Python 3.8.9
2. I have a simple test which I parse using the `astroid.builder._parse_string` function. The `test.py` file looks like below3. 

```
from temp import A, B

A.y = 10

B.y = 5
```

The string form of the above code which I can directly pass into the `_parse_string` function is
```
from temp import A, B\n\nA.y = 10\n\nB.y = 5\n\n
```
3. Call the function
```
from astroid.builder import _parse_string

node, parser_module = _parse_string('from temp import A, B\n\nA.y = 10\n\nB.y = 5\n\n', type_comments=True)
```

### Current behavior
The 2 `_ast.Attribute` objects created for `A.y` and `B.y` have are assigned the same `attr` i.e. y which leads to an incorrect conclusion that they may be duplicates

### Expected behavior
Should they have `attr` as `A.y` and `B.y` respectively? Or some other unique value?

### `python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"` output
2.11.6

**Comment by DanielNoord** [comment]
I don't think this is an `astroid` issue but an `ast` issue right? We just define `_parse_string` to handle different versions of `ast`, but it is not really related to `astroid` internals?

**Comment by gurukamath** [comment]
Ah. You are right. Will raise this in the relevant repo. Thanks
