### ISSUE TITLE
Infinite loop when inferring `from token import *`

### ISSUE THREAD

**Issue by DanielNoord** [PyCQA/astroid#1646]
### Bug description

https://github.com/PyCQA/pylint/commit/600a47e13e3df1ca42521c653ab0ebed5739d485 and its associated primer run creates a crash in `pandas`.

See:
https://github.com/PyCQA/pylint/runs/6914161031?check_suite_focus=true

Last good run:
https://github.com/PyCQA/pylint/runs/6909775916?check_suite_focus=true

I'm not sure though if this is due to the commit or a change in the projects we are linting. The commit of `pandas` changed.

### Configuration

```ini
/
```

### Command used

```shell
/
```

### Pylint output

```shell
/
```

### Expected behavior

/

### Pylint version

```shell
/
```

**Comment by jacobtylerwalls** [comment]
I don't get a failure when launching from the python shell:

```shell
python -c 'from pylint.lint import Run;Run(["pandas.core.arrays._mixins"])'
```

I'm wondering if the fact that we're launching the primer at a location that is not a package (I don't think?) might be contributing to this problem.

**Comment by jacobtylerwalls** [comment]
Closing per https://github.com/PyCQA/astroid/pull/1660#issuecomment-1172900987 in discussion with @DanielNoord.
