### ISSUE TITLE
2.11.6 creates pylint regression

### ISSUE THREAD

**Issue by limburgher** [PyCQA/astroid#1669]
Description of problem:  The recent update [1] seems to have broken pylint (which didn't change in two months). Two days ago, python-dbusmock's pylint tests started to fail [2] with lots of messages like

  dbusmock/mockobject.py:47:7: E1101: Module 'os' has no 'path' member (no-member)
  dbusmock/mockobject.py:762:8: E1101: Module 'os' has no 'write' member (no-member)

These are bogus - of course the standard library `os` module knows about these.

Version-Release number of selected component (if applicable):

python-astroid-2.11.6-1.fc37
python3-pylint-2.13.7-2.fc37.noarch

How reproducible: Always

Steps to Reproduce:
1. git clone https://github.com/martinpitt/python-dbusmock/
2. cd python-dbusmock
3. python3 -m pylint dbusmock/*.py

Additional info:

[1] https://bodhi.fedoraproject.org/updates/FEDORA-2022-4f1ff0f531
[2] https://github.com/martinpitt/python-dbusmock/runs/7035892203?check_suite_focus=true

**Comment by DanielNoord** [comment]
Which python version are those tests running on?

**Comment by martinpitt** [comment]
python3-3.11.0~b3-6.fc37.x86_64 as in current Fedora Rawhide https://bodhi.fedoraproject.org/updates/?packages=python3.11

**Comment by DanielNoord** [comment]
`pylint` doesn't support `Python 3.11` yet. This is because we need changes in `astroid` to be available.

Curent `main` branch of `astroid` does offer support for `Python 3.11`, which will be available in `astroid` `2.12`. I think we're nearing a release but there are still some PRs that we would want to merge before that I think.

**Comment by Pierre-Sassoulas** [comment]
We're close to being able to support 3.11 in pylint but we also need a new release of dill see https://github.com/PyCQA/pylint/pull/6551
