### ISSUE TITLE
Investigate behavior changes from #1606

### ISSUE THREAD

**Issue by jacobtylerwalls** [PyCQA/astroid#1684]
Placeholder issue for investigating behavior changes reported in pylint primer after #1606: https://github.com/PyCQA/pylint/pull/7118#issuecomment-1173141895

I know @DanielNoord is already aware, but just raising visibility to make sure we don't release 2.12 until we have a chance to debug/revert.

**Comment by DanielNoord** [comment]
It's a bit difficult to represent what I did, but here goes.

All messages from `black` are actually fixes 😄 🎉 

We no longer emit messages about defining attributes outside of `__init__`. This is actually an improvement.
Take:
https://github.com/psf/black/blob/b859a377c0bef3793fcceb0efd0086862f6a9365/src/blib2to3/pgen2/conv.py#L68
This shouldn't raise as that attribute is set in the parent class here:
https://github.com/psf/black/blob/b859a377c0bef3793fcceb0efd0086862f6a9365/src/blib2to3/pgen2/grammar.py#L86

This is not related to ``__new__`` but rather to the change in `getattr`, which now correctly looks up values in parent classes before we exit out of the function.

For `Django` the one about `invalid-name` isn't bad as well I think. I think we now correctly infer that this is not the first assignment to `Meta` and therefore the name issue shouldn't be raised here.

The other issues are related to the lookup of instance attributes. I have a fix for this which I'll push shortly.
