### ISSUE TITLE
Update to brain_re.py for third-party regex module

### ISSUE THREAD

**Issue by smontanaro** [PyCQA/astroid#1911]
There's an [open ``pylint`` issue](https://github.com/PyCQA/pylint/issues/5873) regarding module-level constants in the [third-party ``regex`` module](https://pypi.org/project/regex/). It seems the mechanism used by both modules (populate the module namespace by calling ``globals.update()``) is the same, so the fix is pretty similar. Attached is a diff against the current ``astroid`` code.

My apologies for almost certainly not doing this correctly. I didn't bother to read the necessary contribution guidelines. Feel free to beat me with a virtual wet noodle the next time we run into each other. I just wanted to get back to what I was working on (which had nothing to do with ``pylint`` or ``astroid``).

[brain_re.txt](https://github.com/PyCQA/astroid/files/10296110/brain_re.txt)

**Comment by smontanaro** [comment]
Small point about my patch. I did nothing to try and insure it works in the absence of the ``regex`` module. Also, I didn't add any test cases.

**Comment by DanielNoord** [comment]
We would need some tests for this to make sure this doesn't regress in the future. If I find time this week I can look into this. I'm putting it on my todo list!

**Comment by smontanaro** [comment]
Understood. I'll try to take a look. Not being at all familiar with ``astroid``, does my code need to be resilient in the face of a missing ``regex`` module, or does the scaffolding take care of that?

**Comment by DanielNoord** [comment]
Adding it to the `brain` test requirements "should" handle this. But this is a bit of an if. If you make a first draft PR I can definitely help your move this in the right direction. It's often much easier to comment on code than try to find the time and write it yourself 😄

**Comment by smontanaro** [comment]
Pull request created. The tests fail as explained in the PR. I assume smarter people than me will easily be able to figure out what's wrong.

**Comment by Pierre-Sassoulas** [comment]
>  I assume smarter people than me will easily be able to figure out what's wrong.

Thank you for the PR @smontanaro. Though In the words of Steve Jobs the world is made up by people that were no smarter than you 😄
