### ISSUE TITLE
No setup.py in astroid > 2.12.x?

### ISSUE THREAD

**Issue by limburgher** [PyCQA/astroid#1961]
### Steps to reproduce

1. Attempt to build Fedora RPM with updated 2.13.2
2. build runs python3 setup.py
3. No setup.py present.

### Current behavior
In 2.12.14, this works.
### Expected behavior
Successful build

I'm the Fedora package maintainer FYI. If there's documentation addressing this I've missed it.

**Comment by limburgher** [comment]
We use 62.6.0. What command should we use in lieu of python3 setup.py build?

**Comment by DanielNoord** [comment]
We use `pip install .` ourselves to build the local package.

**Comment by DanielNoord** [comment]
Googling for `setup.py deprecated` returns some related issues and SO threads. In general most packages are moving away from `setup.py` towards `pyproject.toml` configs.

**Comment by limburgher** [comment]
I'll check it out, thanks!
