### ISSUE TITLE
St vs. Street in LICENSE

### ISSUE THREAD

**Issue by mtelka** [PyCQA/astroid#1966]
`Franklin St` should be changed to `Franklin Street` twice in the `LICENSE` file to match wording of LGPL-2.1 at https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt.

**Comment by Pierre-Sassoulas** [comment]
This is detected as LGPL v2.1 by github and by Tidelift, changing it would mean more trouble than it's worth.
