### ISSUE TITLE
Unable to parse stringescapeseq in strings

### ISSUE THREAD

**Issue by mjohnson159** [PyCQA/astroid#1975]
### Steps to reproduce

1. Try to parse string with escape char and newline
2. Print out value
3. Value will be short string, no escape character

I am trying to write a custom rule for Pylint to find any strings that are separated via a backslash and raise a warning, e.g.
```py
my_var = "this should \
    throw a warning"
```
to follow my team's programming standards, but I am unable to find any community to ask for advice/help and I was unable to find in the documentation any reference to any python keywords relating to my situation (raw_unicode_escape, unicode_escape, stringescapeseq, escape sequence).

The escape character exists in normal strings in the code and I'm hoping to find a way to identify them via astroid. If this isn't possible, I would like to know as well. As far as I can tell, it doesn't seem possible.

This _does_ work when parsing r-strings, as expected. But I'm trying to find a way to identify escape characters in normal strings within code to flag as a warning via a Pylint custom plugin.

I apologize for opening an issue with this but I had no other way of finding help on this.

Example code
```py
import astroid
tree = astroid.parse('my_var = "this should \
    throw a warning"')
print(tree.body[-1].value.value)
```
output: `'this should     throw a warning'`

### Current behavior

Output is a string with no way to identify escape sequences.

### Expected behavior

Some flag or specific astroid method that allows identifying if/when any escape characters are in normal strings.

### `python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"` output
2.13.3

**Comment by Pierre-Sassoulas** [comment]
Sometime the builtin ast normalize things, if that's the case there's nothing we can do in astroid. But you could use process_tokens directly in the pylint checker. (Not sure that this is the case here, as I can't test right now)

**Comment by DanielNoord** [comment]
Yeah, there is not much we can do here with the parsing of `ast` nodes. Using `process_tokens` is probably the only option.
