### ISSUE TITLE
Function 'f' has no '__code__' member (no-member)

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/astroid#27]
Originally reported by: **Antony Lee (BitBucket: [anntzer](http://bitbucket.org/anntzer), GitHub: @anntzer?)**

----------------------------------------

The following snippet triggers the spurious error given in the title.
```
#!python

def f():
    pass
print(f.__code__)
```
Other attributes, e.g. `__closure__`, trigger the same error.

(duplicate of logilab/pylint#213 but apparently I have to report this here instead)

----------------------------------------
- Bitbucket: https://bitbucket.org/logilab/astroid/issue/27

**Comment by PCManticore** [comment]
Closing this, since we have the new data model (special_attributes on particular node which know how to look for them).
