### ISSUE TITLE
Add Jython to Travis CI

### ISSUE THREAD

**Issue by ceridwen** [PyCQA/astroid#288]
There are some examples/instructions here:
https://www.topbug.net/blog/2012/05/27/use-travis-ci-with-jython/
https://github.com/baztian/travis-jython-template/blob/master/.travis.yml

**Comment by PCManticore** [comment]
Added and it was quite painful, due to things not working out of the box in pip's case with Jython 2.7.0. Issue #301 should be dealing with fixing the problems we're having on Jython.
