### ISSUE TITLE
Consider adding IronPython to supported versions

### ISSUE THREAD

**Issue by ceridwen** [PyCQA/astroid#289]
Now that we're using Travis CI, we might consider supporting and testing on IronPython.  At least one project seems to have IronPython working on Travis: https://github.com/earthreader/libearth/blob/master/.travis.yml

**Comment by PCManticore** [comment]
I don't think it is worth it. The last release that they seemed to have, according to their homepage (http://ironpython.net/), was at the end of 2014. We already have some backwards compatibility problems with Jython and PyPy and it is quite hard to provide a good support story with our current limited resources. I would prefer to invest in CPython and PyPy for now.
