### ISSUE TITLE
Issues with With implementation in 2.0

### ISSUE THREAD

**Issue by PCManticore** [PyCQA/astroid#306]
There are some issues with With, AsyncWith and WithItem in 2.0. There are some variables which are undefined in as_string and AsyncWith is broken in Python 3.5. @ceridwen could you fix these issues? While you're at it, can you remove the use of optional_vars so that we can start using WithItem across the board for both Python 2 and 3?

**Comment by ceridwen** [comment]
Should be fixed as of 5971b00.
