### ISSUE TITLE
tox can't install astroid/pylint for the pylint test environment

### ISSUE THREAD

**Issue by ceridwen** [PyCQA/astroid#321]
This may be a problem in pylint rather than astroid, but somewhere it looks like the requirements are set wrong.

```
Collecting astroid<1.6.0,>=1.5.0 (from pylint==1.6.0)

  Could not find a version that satisfies the requirement astroid<1.6.0,>=1.5.0 (from pylint==1.6.0) (from versions: 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4)

No matching distribution found for astroid<1.6.0,>=1.5.0 (from pylint==1.6.0)
```

**Comment by PCManticore** [comment]
Makes sense. pylint looks for astroid 1.5.0, but that is not released yet. This seems to suggest that the installation step in tox is done before processing the dependencies, where we have a dependency on astroid@master, which should be exactly what pylint wants.

**Comment by PCManticore** [comment]
Should be fixed by https://github.com/PyCQA/pylint/commit/7a9b26b401752845b03b84aee479c370d4cbf951
