### ISSUE TITLE
Put version 1.4.5 on Pypi

### ISSUE THREAD

**Issue by gewthen** [PyCQA/astroid#326]
Version 1.4.5 is missing on Pypi and needs to be packaged and released.

https://pypi.python.org/pypi?%3Aaction=search&term=astroid&submit=search

**Comment by PCManticore** [comment]
I'm not sure what exactly is happening, but both latest astroid and pylint are already on PyPi: https://pypi.python.org/pypi/astroid/1.4.5. It might be worthwhile to ask the PyPi folks themselves about this.

**Comment by gewthen** [comment]
Ahh I see. Didn't show up in the search results... strange.
