### ISSUE TITLE
Why does pylint check for member which are not in __slots__ when assigning but not when accessing?

### ISSUE THREAD

**Issue by sirde** [PyCQA/astroid#332]
IMO pylint shall check when assigning and when accessing an attribute if it is part of __slots__
Currently it only does when assigning. (see my question on SO)
http://stackoverflow.com/questions/36770325/why-does-pylint-check-for-member-which-are-not-in-slots-when-assigning-but-n?noredirect=1#comment61119220_36770325

I have edited the file python_dir\Lib\site-packages\pylint\checkers\classes.py by adding the command: self._check_in_slots(node) in visit attribute. It now checks correctly the access as well as the assignation.

I have no clue if it can have an impact somewhere else ;)

**Comment by PCManticore** [comment]
Thanks! This should be fixed in the next major version of pylint (1.6.0). In the mean time, you can test with the master branch of astroid, paired with the master branch of pylint.
