### ISSUE TITLE
UnicodeWarning

### ISSUE THREAD

**Issue by tianhuil** [PyCQA/astroid#334]
I'm currently on `23e59f8` and I get this error when I pylint my codebase

```
.../python2.7/site-packages/astroid/modutils.py:149: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif norecurs in filenames:
```

It doesn't anything more so I can't be more helpful but perhaps someone who's a unicode wizard can fix this or suppress it.

**Comment by PCManticore** [comment]
Thanks for creating the issue! We dropped support for Python 2 so this error won't be triggered any longer.
