### ISSUE TITLE
Some python files in the project don't have proper license header

### ISSUE THREAD

**Issue by nedn** [PyCQA/astroid#336]
Hi,
I am trying to add pylint/ project to Chromium project (https://codereview.chromium.org/1920403002/). However, the licensechecker of Chromium complains about some python files in astroid/ don't have proper license header, those are:

astroid/brain/builtin_inference.py
astroid/brain/py2stdlib.py
astroid/brain/py2mechanize.py
astroid/brain/py2pytest.py
astroid/brain/py2qt4.py
astroid/brain/py2gi.py
astroid/test_utils.py

Can someone update these files with license header? Thanks a lot!

**Comment by ceridwen** [comment]
Added license headers in 54556be81068cc38e37fb4fcccc126d50de5d405.
