### ISSUE TITLE
Changelog is not being updated

### ISSUE THREAD

**Issue by vfaronov** [PyCQA/astroid#343]
astroid’s [changelog](https://github.com/PyCQA/astroid/blob/master/ChangeLog) has not been updated for releases 1.4.2–1.4.6. I think it should be either maintained or dropped entirely.

Currently [AllMyChanges.com](https://allmychanges.com/p/python/astroid/) is set to track the changelog, which causes it to think that 1.4.1 is the latest release. If you wish to drop the changelog, I can reconfigure it to track PyPI instead.

**Comment by PCManticore** [comment]
The changelog is maintained, although it contains entries from the minor releases, they were not put under a particular section. The changelogs from the minor releases have their Changelog properly updated. My plan is to write some day a script for automatically update the change log across the branches, but I didn't have time for this just yet.

I'm sorry, but the changelog is not going anyway.

**Comment by vfaronov** [comment]
Ah, I see. It’s in the trees referenced by the release tags. Sorry for the confusion.
