### ISSUE TITLE
Setup readthedocs for astroid

### ISSUE THREAD

**Issue by PCManticore** [PyCQA/astroid#344]
Set it up in a similar way to how pylint is:
- [x] docs.astroid.org is using ReadTheDocs for building the documentation
- [x] add ReadTheDocs badge in README
- [x] format the Changelog in a similar way to how the Pylint's ChangeLog is now
- [x] add a `What's new` section

**Comment by zapstar** [comment]
Looks like astroid.org is leading to an ad site...

**Comment by PCManticore** [comment]
@zapstar That's unfortunate. The domain does not belong to us, it was under the original organisation. What we have is just `pylint.readthedocs.io` respectively `astroid.readthedocs.io`. Even `docs.pylint.org` is not our, it has a redirect to the readthedocs page.
