### ISSUE TITLE
Write a just in time debugger for astroid inference

### ISSUE THREAD

**Issue by PCManticore** [PyCQA/astroid#353]
From time to time, we encounter a complex piece of code, where some values were expected to be inferred, but we got other results than what was expected. Trying to debug some of these cases gets insane after a point, due to the huge indirection chains we have in the inference. After a couple of hours spent with sprinkling the code base with print statements and pdb hooks, the idea of having a "tracing"-like debugger for the inference sounds more promising than wasting precious time.

This is just an idea for now, but I imagine this working as in:
- I activate it before calling an .infer method
- the debugger will trace each inference call and will store some data. For instance, I am interested in the context, the context path, each value that was yielded out of an inference entry point, having the inputs of that entrypoint recorded and having the path to that place recorded as well.
- I can use the resulting data generated by the debugger to watch where the inference went. At a given point X, I can see that infer_attribute inferred something which was not supposed to infer. Starting from that point, I can go up to stack to see what values where inferred where and try to find the error
- ideally this would be turned off all the time and it would have almost no performance hit.

**Comment by brycepg** [comment]
I definitely agree with the indirection headaches.

I found a package called [hunter](https://python-hunter.readthedocs.io/en/latest/readme.html) which may be a good start. It allows for selectively tracing functions or functions that match a regex, and to create custom actions, print variables, etc.

Right now i'm using `hunter.trace(function_regex='.*infer.*')`

**Comment by Hnasar** [comment]
was this ever implemented?

**Comment by Pierre-Sassoulas** [comment]
Doesn't seem like it, I don't know what's the reasoning for closing was but I can assume with the high effort label (that I agree with) that it was deemed too complicated and unrealistic to ever be implemented.
