### ISSUE TITLE
check if astroid/brains exist before calling listdir

### ISSUE THREAD

**Issue by 11111010000** [PyCQA/astroid#371]
### Steps to reproduce
1. make sure astroid/brain directory does not exist (happened to my system after release upgrade)
2. import astroid
### Current behavior

```
/usr/local/lib/python3.5/dist-packages/astroid/__init__.py in <module>()
    132     sys.path.append(BRAIN_MODULES_DIR)
    133 # load modules in this directory
--> 134 for module in listdir(BRAIN_MODULES_DIR):
    135     if module.endswith('.py'):
    136         __import__(module[:-3])


FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/astroid/brain'
```
### Expected behavior

no error (creating empty directory astroid/brain makes i.e. pylint work)
### python -c "from astroid import **pkginfo**; print(**pkginfo**.version)" output

1.4.8

**Comment by PCManticore** [comment]
I am not sure what happened here, but brain always exists. If it does not, then your installation is broken and you should reinstall astroid.
