### ISSUE TITLE
Enum.__members__ not found

### ISSUE THREAD

**Issue by degustaf** [PyCQA/astroid#376]
### Steps to reproduce
This is an issue in python 2.7, but not in 3.5.  I have not tested other versions.
Reported by @AdamWill in PyCQA/pylint#1165, but is an astroid issue.
```
>>> node = astroid.builder.extract_node('''
... import enum
... class Color(enum.Enum): #@
...     red = 1''').getattr('__members__')
```

### Current behavior
```
Traceback (most recent call last):  File "<stdin>", line 1, in <module>  File "/home/degustaf/pylint/.tox/py27/local/lib/python2.7/site-packages/astroid/scoped_nodes.py", line 1414, in getattr
    context=context)
astroid.exceptions.AttributeInferenceError: '__members__' not found on <ClassDef.Color l.3 at 0x7f620067f490>.
```

### Expected behavior
Should return an object representing an Ordered dict.

**Comment by PCManticore** [comment]
Works in master, although it returns an Uninferable. The element is present though, which is just enough for now.
