### ISSUE TITLE
Support for sqlalchemy

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/astroid#39]
Originally reported by: **Claudiu Popa (BitBucket: [PCManticore](http://bitbucket.org/PCManticore), GitHub: @PCManticore)**

----------------------------------------

Currently pylinting sqlalchemy code gives some false positives for E1120 (no-value-for-parameter)

I've attached sample code which exhibits this problem.

```
#!bash

$ pylint --version
pylint 1.1.0, 
astroid 1.0.1, common 0.61.0
Python 2.7.3 (default, Aug  9 2012, 17:23:57) 
[GCC 4.7.1 20120720 (Red Hat 4.7.1-5)]

$ python -c "import sqlalchemy; print sqlalchemy.__version__"
0.9.4

$ pylint --reports=no sqlalchemy_testcase.py
************* Module sqlalchemy_testcase
E: 20, 4: No value passed for parameter 'dml' in function call (no-value-for-parameter)
```

The insert function is decorated, and the decorator fills in the 'dml' parameter. The callee providing it is an error.

I could potentially look at this myself but won't have the time to do so immediately.

Reported by Robbie Coomber on pylint-brain.

----------------------------------------
- Bitbucket: https://bitbucket.org/logilab/astroid/issue/39

**Comment by PCManticore** [comment]
Closing this. I don't think this issue should be here, but rather in Pylint.

**Comment by raylu** [comment]
Is there an issue in pylint that tracks this? I found https://github.com/PyCQA/pylint/issues/194 which appears to be closed because it should be handled in pylint-brain, now astroid.
