### ISSUE TITLE
Wrong reports "bad operand type for unary ~: _isnan (invalid-unary-operand-type)"

### ISSUE THREAD

**Issue by sscherfke** [PyCQA/astroid#424]
### Steps to reproduce
1. Create a script:
    ```python
    import numpy
    import pandas


    _ = ~numpy.isnan(3)
    _ = ~pandas.isnull(3)
    ```
2. Run `pylint script.py`

### Current behavior

```
************* Module script
E:  6, 4: bad operand type for unary ~: _isnan (invalid-unary-operand-type)
E:  6, 4: bad operand type for unary ~: _isnan (invalid-unary-operand-type)

----------------------------------------------------------------------
Your code has been rated at -15.00/10 (previous run: -15.00/10, +0.00)
```
### Expected behavior

```
--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output

1.5.2

**Comment by mhooreman** [comment]
Hi,
Is there some news about that? I had to add `disable=invalid-unary-operand-type` in `.pylintrc`, which I don't really like.
Thanks!

**Comment by PCManticore** [comment]
No progress has been made yet on this issue as no one worked on it just yet.

**Comment by polosatik** [comment]
Is there any way to upvote this?

**Comment by PCManticore** [comment]
@polosatik The fastest way to get this fix is to submit a PR that adds `pandas` as an astroid brain plugin, in a similar fashion to the `numpy` one: https://github.com/PyCQA/astroid/blob/master/astroid/brain/brain_numpy.py Given that we're all volunteers, there's no priority per se regarding on what issues we work on.

**Comment by sscherfke** [comment]
I can no longer reproduce the exact issue I initially reported with the latest git versions. Not sure if it was fixed by accident or if my pylintrc has some hidden ignores for this …

**Comment by sscherfke** [comment]
A brain like this seems to fix the issue:
```python
# astroid/brain/brain_pandas.py
"""
Astroid hooks for pandas.

"""
import astroid


def pandas_funcs():
    return astroid.parse(
        """
        def isnull(obj): return obj is None
        """
    )


astroid.register_module_extender(astroid.MANAGER, 'pandas', pandas_funcs)
```
I am not sure though what I can/should use as return value for the function? 🧠

**Comment by PCManticore** [comment]
That looks good to me @sscherfke What return value are you referring to?

**Comment by sscherfke** [comment]
The return value of the fake `isnull` function. It’s supposed to return a `bool` or an array-like (numpy array, list?) of bools.

**Comment by hippo91** [comment]
@sscherfke it seems that this bug does not occur anymore with latest `pylint` and `astroid` version.
For example linting:
```
#pylint: disable=missing-module-docstring
import numpy
import pandas


_ = ~numpy.isnan(3)
_ = ~pandas.isnull(3)
```
gives:

```

--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)
```

```
pylint --version
pylint 2.8.0-dev1
astroid 2.6.0-dev1
Python 3.9.1 (default, Dec 30 2020, 11:18:33) 
[GCC 7.5.0]
```

```
pip freeze
isort==5.7.0
lazy-object-proxy==1.5.2
mccabe==0.6.1
numpy==1.20.1
pandas==1.2.3
python-dateutil==2.8.1
pytz==2021.1
six==1.15.0
toml==0.10.2
wrapt==1.12.1
```
