### ISSUE TITLE
astroid extract_node fails when given a single string

### ISSUE THREAD

**Issue by brycepg** [PyCQA/astroid#508]
### Steps to reproduce
1. run the below code

```
import astroid
astroid.extract_node("'astring'")
```

### Current behavior

Astroid raises an IndexError:

```
~/.local/lib/python3.6/site-packages/astroid/builder.py in extract_node(code, module_name)
    431 
    432     if not extracted:
--> 433         extracted.append(tree.body[-1])
    434 
    435     extracted = [_extract(node) for node in extracted]

IndexError: list index out of range
```

### Expected behavior

No exception

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output

2.0.0

**Comment by PCManticore** [comment]
This makes sense, the parser assumes that every script you parse with it is a Module. In this case that string will become the docstring of the module, resulting in an empty body. We should raise a completely different error in this case though.
