### ISSUE TITLE
Add a reveal_inference function for debugging

### ISSUE THREAD

**Issue by brycepg** [PyCQA/astroid#522]
[mypy](https://mypy.readthedocs.io/en/latest/cheat_sheet_py3.html) has a nifty function called `reveal_type` which simply prints out the types of the inferred variables as it runs. I think astroid could use something like this for debugging inference.

The inference transform system could be used to create an inference_tip for functions called `reveal_inference` which print out node inference information depending certain keywords passed to the function. This would help debugging large inference chains.

### Example

The following code 

```
import astroid
astroid.extract_node("""
a = 1
a = reveal_inference(a)
b = a + 1
b #@
""").inferred()
```

Might print out inference information about how `Name.a infers` to `1`

keyword args to `reveal_inference` could be added to reveal additional information or to kickoff a debugger

Note that `reveal_inference` could be used inside pylint.

**Comment by PCManticore** [comment]
This sounds similar to the idea we had in https://github.com/PyCQA/astroid/issues/353. The idea sounds good to me, but I wouldn't want it to be put some sort of magic function call inside a string, as it is in your example. A function, something along the lines of `astroid.reveal_inference` would be a lot better. I'm not sure how this will be used inside pylint? Probably we'll use just for debugging purposes.

**Comment by brycepg** [comment]
Closing in favor of #353
