### ISSUE TITLE
Please remove tests from the pip-installed version

### ISSUE THREAD

**Issue by cprogrammer1994** [PyCQA/astroid#535]
### Steps to reproduce
1. `pip install astroid`

### Current behavior

![image](https://user-images.githubusercontent.com/11232402/38683629-989a7b9e-3e76-11e8-8ee6-7152e10b280e.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/11232402/38683674-b56df566-3e76-11e8-8feb-da2c3ac2c185.png)

```
python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"
1.6.3
```

**Comment by PCManticore** [comment]
This should work now in master branch.

**Comment by cprogrammer1994** [comment]
Thank you! It is much smaller in **1.6.4** 😄 

![image](https://user-images.githubusercontent.com/11232402/40585370-14a3129e-61ba-11e8-92e9-82f1ec051967.png)

```
python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"
1.6.4
```
