### ISSUE TITLE
astroid cannot import modules from wheels

### ISSUE THREAD

**Issue by leifwalsh** [PyCQA/astroid#541]
### Steps to reproduce
1. Have a .whl file on the path, and code that imports it
2. Run pylint on the importing code

### Current behavior
pylint reports an error that it cannot import the module

### Expected behavior
pylint doesn't report an error

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output
astroid 1.6.3, pylint 1.8.1

I believe the fix would be to add `'.whl'` to this list:  https://github.com/PyCQA/astroid/blob/e0a298df55b15abcb77c2a93253f5ab7be52d0fb/astroid/manager.py#L188

I've patched astroid locally and this does allow astroid to import the module.  I'm surprised we haven't seen this before, I think an older version of pylint also failed to astroid-import the module, but just didn't complain about it?

**Comment by PCManticore** [comment]
Hey @leifwalsh Thanks for creating the issue! Yes that fix might actually solve this problem and sounds reasonable. Would you mind sending a PR with that?
