### ISSUE TITLE
Allow for stub files that explicitly state what the import tree is at run time

### ISSUE THREAD

**Issue by rawrgulmuffins** [PyCQA/astroid#551]
### Steps to reproduce
1. Create a sub-package which is lazy loaded in a top level module
2. Run pylint on top level package with `from <top_level> import <sub_module>`

### Current behavior
```
:) pylint top_level/sub_module/bin/__main__.py
************* Module __main__.py
E:  9, 0: No name 'sub_package' in module 'top_level' (no-name-in-module)

------------------------------------------------------------------
Your code has been rated at 1.67/10 (previous run: 1.67/10, +0.00)
```

### Expected behavior
If I've created a stub file that contains something like

```
top_level = sub_module
```

Or potentially another format

```
top_level.sub_module
top_level.another_module
```

Then 
```
:) pylint top_level/sub_module/bin/__main__.py.py

------------------------------------------------------------------
Your code has been rated at 10/10 (previous run: 10/10, +0.00)
```

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output

```
python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"
1.6.2
```

**Comment by PCManticore** [comment]
astroid doesn't work with stub files, it needs the actual source code to analyze the AST. Can you post the structure of a small project that reproduces this problem for you? It's kind of hard to infer it from path names.
