### ISSUE TITLE
Module.stream documentation error

### ISSUE THREAD

**Issue by johnburnett** [PyCQA/astroid#555]
It looks like there was an incorrect(?) deprecation note added to Module.stream in [this](https://github.com/PyCQA/astroid/blame/master/astroid/scoped_nodes.py#L421) commit, based on [this comment](https://github.com/PyCQA/astroid/blob/master/ChangeLog#L840) made in the changelog.  I think it was just Module.file_stream (now removed) that was deprecated, and Module.stream was intended to be the replacement?  If not, what replaces the replacement?

**Comment by PCManticore** [comment]
Hey thanks for the report! `stream()` is not deprecated, `file_stream` was. Sorry for the confusion.
