### ISSUE TITLE
astroid 2.0.0 chokes on recursion

### ISSUE THREAD

**Issue by hroncok** [PyCQA/astroid#557]
### Steps to reproduce

https://github.com/PyCQA/astroid/blob/master/astroid/tests/testdata/python3/data/joined_strings.py

```python
import astroid
import pathlib
astroid.MANAGER.optimize_ast = True
source = pathlib.Path('joined_strings.py').read_text()
builder = astroid.builder.AstroidBuilder()
tree = builder.string_build(source)
```

### Current behavior with 1.6

No exception.

### Current behavior with 2.0

    RecursionError: maximum recursion depth exceeded

This breaks asttokens tests: https://github.com/gristlabs/asttokens/issues/16

**Comment by PCManticore** [comment]
I think this is fine. In the past we used to have a *hack* for supporting joining thousands of strings together, but we decided to remove that hack with this release. There's no need to support such an use case as it's not going to happen in real life, and if it does, then there's no expectation for astroid to work on that IMO. What `asttokens` might be doing is running `astroid` over the data test files from astroid, as I can see from their repo, but I suggest that they should remove the `joined_strings` file as it's no longer a supported use case. Here's the removal of that hack for reference https://github.com/PyCQA/astroid/commit/517697667497e4df4c7e44d9dba42134ee6f47bc.
