### ISSUE TITLE
Add of a DEP file

### ISSUE THREAD

**Issue by WaldoFR** [PyCQA/astroid#570]
Hi, 

Sorry if this content is available somewhere, I've been looking for a file gathering all dependencies required by astroid 1.6.5 ( newest versions do not seem to include the feature neither), and I found nothing. It's a huge problem when trying to run the setup in offline mode. 

In the pylint project, there is a DEP file including every version of each dependencies to install before running the command `python setup.py install`. I'd like to know where I could get the information in the current project.

Regards,
WaldoFR

**Comment by brycepg** [comment]
You can find the requirements in `astroid/__pkginfo__.py` under install_requires

**Comment by WaldoFR** [comment]
Thank you @brycepg  :)
