### ISSUE TITLE
OSError attributes are incorrectly ClassDefs

### ISSUE THREAD

**Issue by brycepg** [PyCQA/astroid#580]
The follwing code
```python
import astroid
[fname] = astroid.extract_node("""
try:
    pass
except OSError as error:
    error.filename #@
""").infer()
print(fname)
```
Gives
```
ClassDef.filename(name='filename',
                  doc='exception filename',
                  decorators=None,
                  bases=[],
                  body=[ <Const.str l.0 at 0x702e55fcc978>,
                    <Const.str l.0 at 0x702e55fcc9b0>])
```

This causes false-positives such as `filename.startswith` because `filename` should be a string.
`.locals['filename']` has this ClassDefs. `OSError.filename` is a `member_descriptor` in python.

**Comment by PCManticore** [comment]
This might be a `raw_building` bug. It might be fixed in the `2.0` branch where we have a new raw building, but it might not be even inferred as a string then, so this seems like a good use case for either a `brain` tip or for some modification in `objectmodel`.

**Comment by brycepg** [comment]
I can confirm that it is a raw_building thing at `object_build_datadescriptor`: https://github.com/PyCQA/astroid/blob/master/astroid/raw_building.py#L175

**Comment by PCManticore** [comment]
Can you also check with the 2.0 branch to see what it gets inferred to? Most likely not a string, just curious if it's better by any chance in this case.

**Comment by brycepg** [comment]
Yeah it's referred to an `instance of member_descriptor` in the `2.0` brach. I looks like it accepts any getattr and returns an instance of its self which would fix this issue I think
