### ISSUE TITLE
type.__new__ attribute infers to both type.__new__ and object.__new__

### ISSUE THREAD

**Issue by brycepg** [PyCQA/astroid#581]
Example:

```python
import astroid
print(astroid.extract_node("""
type.__new__
""").inferred())
```

Results in `[<BoundMethod __new__ of builtins.type at 0x126350295329928, <BoundMethod __new__ of builtins.object at 0x126350078306680]`
The above code should only infer to BoundMethod of `type.__new__`

This is causing some issues and hacks in the code base including https://github.com/PyCQA/astroid/blob/master/astroid/bases.py#L452 I think

**Comment by PCManticore** [comment]
Yes, should be great to fix this.
