### ISSUE TITLE
`NodeNG.get_children` yields nodes in inconsistent order

### ISSUE THREAD

**Issue by brendanator** [PyCQA/astroid#585]
### Steps to reproduce
1. Write function with args, default args, annotations, varargs, kwargs
2. Parse and call get_children

### Current behavior
Nodes are yielded in this order
- args
- defaults
- kwonlyargs
- kw_defaults
- annotations
- varargannotation
- kwargannotation
- kwonlyargs_annotations

### Expected behavior
- Nodes are yielded in order they appear in source code
- Varargs and kwargs are also yielded

### Other example
`IfExp.get_children` yields `test` node before `body` node

### Possible Solution
I would expect all fields that aren't identifiers in the [python3 AST](https://docs.python.org/3/library/ast.html#abstract-grammar) to be yielded in the order they appear in the source code

It seems as though astroid nodes are based on [python2.7 AST](https://docs.python.org/2.7/library/ast.html#abstract-grammar) with additional information from the later version added. I think it would be better to base the astroid nodes on the latest python AST and get the builder code to convert from python2.7 AST. This solution means that more information is retained in the AST and cleanly solves this issue

I may provide a PR for this but want to check:
- are there any problems with this solution
- what needs looking out for when implementing this?
- how would other libraries be affected?
- is this likely to be merged?

**Comment by nickdrozd** [comment]
I messed with `get_children` in https://github.com/PyCQA/astroid/commit/52e67656d7728f8ba958c9c35bef3a44013ad6dd, and https://github.com/PyCQA/astroid/commit/228e34db1fdc4935df0d3d63f24e1e484dddf7e4 made some corrections to address your issue. I don't know if it fixed all of it.

That said, there does not seem to be a requirement that the child nodes get yielded in any particular order:
```
    def get_children(self):
        """Get the child nodes below this node.

        :returns: The children.
        :rtype: iterable(NodeNG)
        """
```
What is the use case for requiring that the children are yielded "in the order they appear in the source code"? Why not yield them alphabetically (e.g. `body`, `orelse`, `test` for `While` nodes)? I have no objection to changing the order to match some convention, but making a particular order a requirement seems a little odd to me.

**Comment by PCManticore** [comment]
As @nickdrozd I'm also not sure we were promoting `get_children` as traversing the tree in any given order, but we can address this if it doesn't make sense right now, as long as it is feasible.

Regarding the second issue, you have to take in account that `astroid` started as compatibility layer between Python 2 up to the latest Python 3, so it needed its quirks in order to be compatible with 6-7 versions. I'm not opposed to changing `varargs` and `kwargs` but this also means changing it in `pylint` as well as in the third party plugins.

**Comment by brendanator** [comment]
Cool, I will submit a PR for the ordering issue then

I will also have a look to see if the adding in the missing nodes causes too many problem in pylint. What is the best way to set pylint up to point at a local version of astroid?

**Comment by PCManticore** [comment]
What I usually do is to install both in editable mode in a virtualenv:
```
pip install -e . (for astroid)
pip install -e . (for pylint)
```
Then any modification I write in each of those repos is instantly reflected at CLI. Hope this helps!

**Comment by brendanator** [comment]
As #595 has been closed I am closing this too
