### ISSUE TITLE
[Debian] Do you have an (rough) ETA for 2.0.0

### ISSUE THREAD

**Issue by P-EB** [PyCQA/astroid#590]
Dear astroid devs,

As python3.7 became the main python release into Debian, many things broke, including our current packaged version of astroid.

To get some clear idea about how and when we'll be able to fix this specific package, I'm trying to find when your 3.7 compatible release will get on board.

In the current ChangeLog, the ETA for 2.0.0 is unknown. But maybe as devs you have a better idea regarding this?

Cheers! :)

**Comment by PCManticore** [comment]
Hi @P-EB I plan to release it this week. In the meantime, you can use the dev release if you need Python 3.7 support.

**Comment by P-EB** [comment]
@PCManticore Nah, it's not an emergency.

**Comment by PCManticore** [comment]
Just released pylint 2.0 and astroid 2.0. Please give it a go and let us know if you have any issues!

**Comment by P-EB** [comment]
Thanks!
