### ISSUE TITLE
Move away from imp

### ISSUE THREAD

**Issue by PCManticore** [PyCQA/astroid#594]
Now that we only support Python 3, we should move away from `imp` to `importlib`.

Check https://bugs.python.org/issue34056 and https://github.com/PyCQA/astroid/issues/593#issuecomment-405079163.

**Comment by sushobhit27** [comment]
@PCManticore can I work on this as this seems to be simple find replace issue.

**Comment by PCManticore** [comment]
@sushobhit27 Please do!

**Comment by pkolbus** [comment]
I'm running into the `DeprecationWarning` as well, as enabling this warning is recommended by the [Python 3.9 release notes](https://docs.python.org/3.9/whatsnew/3.9.html); [PEP 594](https://www.python.org/dev/peps/pep-0594/#imp) indicates a desire to remove `imp` in 3.10 which is now starting development. @degustaf has made excellent headway on this in #686 but this work has stalled.

@PCManticore @degustaf any objection if I take this (and #681) over?

**Comment by degustaf** [comment]
@pkolbus I have no issue with you taking this over. I have been busy on other things.
