### ISSUE TITLE
Performance issues with astroid 1.6.X and possibly astroid 2.X as well

### ISSUE THREAD

**Issue by dickreuter** [PyCQA/astroid#605]
When using asteroid 1.6.5 pylint becomes very slow as described here
https://github.com/PyCQA/pylint/issues/2198
"took a simple test program like the one above and varied the installed versions of Pandas, Numpy, Pylint, and astroid. I found that the Pandas, Numpy, and Pylint versions do not matter at all, I tested several versions of each from Summer 2017 up until today. But astroid <= 1.6.1 took only about 20-30 seconds, whereas anything >= 1.6.2 took 8-10 minutes! This also applies to the 2.x.y releases of Pylint and astroid, they take forever to analyze the simple test program."

Any suggestions what I can do about this?

**Comment by PCManticore** [comment]
@dickreuter Would an IBAN work for you? I understand your frustration but it gets annoying at this point.

**Comment by PCManticore** [comment]
https://github.com/PyCQA/astroid/pull/630 That is the culprit, unfortunately a lot changed so there are quite a few of tests failing.

**Comment by michael-lefkowitz-techlabs** [comment]
any chance this ticket can be re-opened?

pylint is still taking over a minute to lint a short `.py` file that contains a very long string (65510 chars).
```
pylint 2.6.0
astroid 2.4.2
Python 3.8.0 (default, Feb 25 2021, 22:10:10) 
[GCC 8.4.0]
```
