### ISSUE TITLE
Decorator `attrib` unsupperoted where `attr.ib` is

### ISSUE THREAD

**Issue by gavento** [PyCQA/astroid#628]
While pylint supports `attr` classes with `attr.ib` attributes, it does not support the same with `attr.attrib`, which is an alias preferred by some.

### Steps to reproduce
1. `pylint attrib_test.py` with:
```python
import attr
from attr import attrib, attrs

@attr.s
class D1:
    d = attr.ib()

@attrs
class D2:
    d = attrib()

@attr.s
class OK:
    x1 = attr.ib(type=D1)
    x2 = attr.ib(type=D2)

    def test(self):
        return (self.x1.d, self.x2.d)

@attrs
class Err:
    x1 = attrib(type=D1)
    x2 = attrib(type=D2)

    def test(self):
        return (self.x1.d, self.x2.d)
```
### Current behavior

Class `OK` reports no errors while `Err` reports:
```
[... snip docstring and too-few-methods lints]
tst.py:26:16: E1101: Instance of '_CountingAttr' has no 'd' member (no-member)
tst.py:26:27: E1101: Instance of '_CountingAttr' has no 'd' member (no-member)
[... snip docstring and too-few-methods lints]
```
Note the problem is not in how classes `D1`, `D2` were declared (`attr.ib` or `attrib`).

### Expected behavior

class `Err` should also return no errors.

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output

2.1.0

**Comment by gavento** [comment]
It seems that recognizing `attr` annotations in https://github.com/PyCQA/astroid/blob/master/astroid/brain/brain_attrs.py is incomplete (both for classes and attributes).

**Comment by PCManticore** [comment]
@gavento That's true. Would you like to submit a patch?
