### ISSUE TITLE
Add support for builtin constructors

### ISSUE THREAD

**Issue by pylint-bot** [PyCQA/astroid#64]
Originally reported by: **Claudiu Popa (BitBucket: [PCManticore](http://bitbucket.org/PCManticore), GitHub: @PCManticore)**

----------------------------------------

We should understand the following function calls and map them to their syntactic counterpart.

```
#!python

list([4, 5, 6])
set((1, 2, 3))
tuple(('a', 'b', 'c')
frozenset({1: 2})
dict(a=4, b=5)
```
Currently, astroid understand list/set/tuple calls without heterogenous elements and only with const nodes. Using tuple(('a', tuple(list([4]))) might not work right now, for instance.
The tricky part is the frozenset, which can't be mapped to a Set and it doesn't have an equivalent AST node.

----------------------------------------
- Bitbucket: https://bitbucket.org/logilab/astroid/issue/64

**Comment by PCManticore** [comment]
Not sure why this is still open. We do support frozensets for a while now.
