### ISSUE TITLE
_NonDeducibleTypeHierarchy exception on valid code

### ISSUE THREAD

**Issue by condemil** [PyCQA/astroid#644]
### Steps to reproduce
1. Create file `test.py` with the following content:

```python
import collections.abc
from typing import (
    TYPE_CHECKING,
    Any,
    MutableMapping,
)

if TYPE_CHECKING:
    BaseClass = MutableMapping[str, Any]
else:
    BaseClass = collections.abc.MutableMapping


class TestBaseException(BaseClass):
    pass

class TestException(TestBaseException):
    pass


def test():
    try:
        a = None
    except TestException:
        raise
    except Exception:
        pass
```

2. Run pylint with `pylint test.py`
3. See `astroid.exceptions._NonDeducibleTypeHierarchy` error

### Current behavior

astroid.exceptions._NonDeducibleTypeHierarchy raised

### Expected behavior

no error

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output

2.1.0

**Comment by condemil** [comment]
@asvetlov FYI

**Comment by PCManticore** [comment]
Thanks for reporting the issue!
