### ISSUE TITLE
typed-ast 1.3.0 supports Python 3.7

### ISSUE THREAD

**Issue by The-Compiler** [PyCQA/astroid#646]
With https://github.com/python/typed_ast/pull/78 the recent 1.3.x release of typed-ast fully supports Python 3.7. Thus, the [condition](https://github.com/PyCQA/astroid/blob/master/astroid/__pkginfo__.py#L33) in `__pkginfo__.py` can probably be removed (or changed so that Python < 3.6 is only required for typed-ast < 1.3.0).

**Comment by PCManticore** [comment]
Thanks @The-Compiler that's great!

**Comment by The-Compiler** [comment]
Awesome, thanks for the quick fix! Is there any timeline for the next release already? If not, don't worry, I usually tell people I don't do ETAs for work I do in my free time :wink:

**Comment by PCManticore** [comment]
Sure thing! It's definitely going to happen this month, hopefully by next week.
