### ISSUE TITLE
astroid blocks for updates to mypy

### ISSUE THREAD

**Issue by astir13** [PyCQA/astroid#652]
### Steps to reproduce
1. try to create a pipenv with latest astroid and mypy inside
2. the dependency of astroid to typed-ast <1.3.0 conflicts with mypy dependency >= 1.3.1 (see https://python-forum.io/Thread-latest-astroid-dependencies-break-mypy?pid=72966#pid72966)
3. the pipenv -v lock command issues an error

### Current behavior
error from pipenv -v lock

### Expected behavior
would be nice if astroid could reevaluate its dependency to typed-ast to allow other libraries to use more modern typed-ast 

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output
2.1.0

astroid==2.2.0 requires lazy-object-proxy, six, typed-ast<1.3.0
mypy==0.670 requires mypy-extensions<0.5.0,>=0.4.0, typed-ast<1.4.0,>=1.3.1

Workaround is of course to set mypy to use version 0.660 in the Pipfile.

**Comment by macbeth322** [comment]
I was able to work around this by using python3.7; but it would be nice to still be able to use python3.6.

**Comment by PCManticore** [comment]
Thanks @astir13 for creating this issue. The restriction for `typed_ast<1.3` was removed and it's going to be part of astroid 2.2.4 once [this build](https://travis-ci.org/PyCQA/astroid/builds/501943826) finishes
