### ISSUE TITLE
Expose multi-line function argument type annotation comments

### ISSUE THREAD

**Issue by AWhetter** [PyCQA/astroid#665]
### Feature Request
Say we are parsing the following function:

```python
def sum(
        a,  # type: int
        b,  # type: int
):
    # type: (...) -> int
    return a + b
```

There is no way to access the type annotation comments for the individual `a` and `b` arguments, only the function itself.
`typed_ast` exposes these type comments through the attribute `type_comment` on each `arg` node:

```python
>>> import typed_ast
>>> module = typed_ast.ast3.parse('''def sum(\n    a,  # type: int\n    b,  # type: int\n    ):\n    # type: (...) -> int\n    return a + b''')
>>> module.body[0].args.args
[<typed_ast._ast3.arg object at 0x7f318d7cd0b8>, <typed_ast._ast3.arg object at 0x7f318d7cd0f0>]
>>> module.body[0].args.args[0].type_comment
'int'
```

### Desired behavior
We could add a `type_annotation` attribute to the `AssignName` node, but for regular assignments this is redundant information because type comments are exposed on the parent `Assign` node.
So the parent `Arguments` node seems like the right place for it to go. I'm proposing the addition of a `type_comment_args` attribute on the `Arguments` node that contains a list of the type comments, one for each argument using a None for arguments that are missing a comment.

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output

2.2.5

**Comment by PCManticore** [comment]
This sounds like a sensible suggestion, makes sense having it.
