### ISSUE TITLE
Fail when importing collections on python3.8

### ISSUE THREAD

**Issue by jkonecny12** [PyCQA/astroid#677]
### Steps to reproduce
1.  Install python3.8.0b1
2.  Use my script below
3.  Run pylint from pip on this script (python3 -m pylint ./reproducer.py)

### Current behavior

<mock-chroot> sh-5.0# python3 -m pylint ./test.py
************* Module test
test.py:4:0: E0001: Cannot import 'collections' due to syntax error 'invalid syntax (<unknown>, line 96)' (syntax-error)
test.py:7:4: C0103: Constant name "c" doesn't conform to UPPER_CASE naming style (invalid-name)

### Expected behavior

Everything should be fine, although I'm not sure about the UPPER_CASE. Is that correct? 

### ``python3 -m pylint --version`` output

__main__.py 2.3.1
astroid 2.2.5
Python 3.8.0b1 (default, Jun  5 2019, 08:48:48) 
[GCC 9.1.1 20190503 (Red Hat 9.1.1-1)]

------------------------------
### Reproducer script

```
#!/usr/bin/python3
""" My small reproducer """

import collections

if __name__ == "__main__":
    c = collections.Counter()
    c['a'] += 1
    print("abc", c)
```

------------------------------

Not sure if this is really astroid issue or pylint issue. Please tell me and I'll create this issue on pylint.

**Comment by degustaf** [comment]
This is an astroid issue. If you look at the [collections module in 3.8](https://github.com/python/cpython/blob/3.8/Lib/collections/__init__.py), you can see that they are using the new positional-only arguments, which astroid can't handle yet.

**Comment by PCManticore** [comment]
@degustaf is right. The released versions of `pylint` and `astroid` don't support Python 3.8 yet. `astroid`'s master supports Python 3.8, while for `pylint` there are still a couple of failing tests. We'll probably have a release before the official launch of Python 3.8.
