### ISSUE TITLE
Dependency on typed-ast breaks with Pylint and mypy

### ISSUE THREAD

**Issue by Maddosaurus** [PyCQA/astroid#696]
### Steps to reproduce
1. Starting from a clean Pipfile with no pinned versions with just mypy and pylint as requirements, do a `pipenv install`:
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
pylint = "*"
mypy = "*"

[packages]

[requires]
python_version = "3.6"
```
2. Observe pipenv failing the install command with `There are incompatible versions in the resolved dependencies.`
3. By manually pinning astroid to `==2.2.5`, this can be mitigated

### Current behavior
Pipenv fails with `There are incompatible versions in the resolved dependencies.`  
`ERROR: Could not find a version that matches typed-ast<1.3.0,<1.5.0,>=1.4.0`
### Expected behavior
Pipenv is able to write a Pipfile.lock

This looks like #639 again, although I'm not sure.  

Any help would be appreciated!

**Comment by PCManticore** [comment]
This *should* be fixed by https://github.com/PyCQA/astroid/commit/3c57b6e16c3d6eb3eac52d6337d5e07ab7de29e5 when it's released as part of astroid 2.3.1.
