### ISSUE TITLE
Regression in astroid 2.3.0 for children of dataclasses

### ISSUE THREAD

**Issue by lbenezriravin** [PyCQA/astroid#698]
### Steps to reproduce
Run pylint on the following code:
```
from dataclasses import dataclass

@dataclass
class Ant:
    cat: int

class Bat(Ant):
    def dog(self):
        return self.cat

print(Bat(5).dog())
```

### Current behavior
```
foo.py:9:15: E1101: Instance of 'Bat' has no 'cat' member (no-member)
```

### Expected behavior
No error. Running the script completes without error. Furthermore, reverting to astroid 2.2.5 solves this problem.

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output
`2.3.0`

Thank you for your work on an amazing tool!

**Comment by PCManticore** [comment]
Thanks for reporting an issue. This should already be fixed by https://github.com/PyCQA/astroid/commit/3e4eac76e9abfa0400fa07b58c61973ac5495bd2 which will be part of 2.3.1 shortly.

**Comment by lbenezriravin** [comment]
Thank you for your very prompt response and solution!
