### ISSUE TITLE
Nested lambdas trigger "undefined-variable" warnings when referring to arguments in enclosing lambdas

### ISSUE THREAD

**Issue by vrikodhara** [PyCQA/astroid#714]
### Steps to reproduce
1. Create a file with the following code:
``` python
a = lambda f: lambda n: lambda x: f(x * n)
print(a(lambda x: x + " "  + x)(3)("#"))
```
2. Run lint

### Current behaviour
Get the following message:
```
C:  1, 0: Missing module docstring (missing-docstring)
C:  1, 0: Invalid constant name "a" (invalid-name)
E:  1,34: Undefined variable 'f' (undefined-variable)
E:  1,40: Undefined variable 'n' (undefined-variable)
```

### Expected behavior
"f" and "n" are defined and should not trigger warning.

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output
2.3.2

**Comment by PCManticore** [comment]
Thanks for opening an issue. I cannot reproduce it using the latest `pylint`:
```
pylint 2.5.0-dev1
astroid 2.4.0
Python 3.6.5 (default, May  7 2018, 10:07:07)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```
with
```
a.py:1:0: C0114: Missing module docstring (missing-module-docstring)
a.py:1:0: C0103: Constant name "a" doesn't conform to UPPER_CASE naming style (invalid-name)
```

Also this issue should have been created on pylint's issue tracker, not here.

**Comment by vrikodhara** [comment]
Sorry. I had an older version of astroid and pylint.
