### ISSUE TITLE
"unexpected-keyword-arg" (Unexpected keyword argument 'text') error on subprocess.check_output

### ISSUE THREAD

**Issue by avancil** [PyCQA/astroid#722]
### Steps to reproduce
1. Python 3.6.8
2. check_output("ls", preexec_fn=lambda: None)
3. pylint -E

### Current behavior
temp.py:9:0: E1123: Unexpected keyword argument 'preexec_fn' in function call (unexpected-keyword-arg)

### Expected behavior
No error

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output
2.3.3

See recently closed #715. All Popen arguments need to be supported.

**Comment by EugeniuZ** [comment]
Looks like the fix was not included in the package from pypi repo (release 2.3.3).  It is not in the released package (2.3.3) on github too.

**Comment by socketpair** [comment]
Triggered in Fedora 31 + updates

**Comment by socketpair** [comment]
See also PyCQA/pylint#1393

**Comment by crobinso** [comment]
I confirmed this is fixed with astroid git. fedora packages are still using old code.
