### ISSUE TITLE
Create astroid module from a string using AstroidManager

### ISSUE THREAD

**Issue by thisch** [PyCQA/astroid#725]
For the read-from-stdin feature in pylint an AST is constructed using 

```py
AstroidBuilder(MANAGER).string_build(data, modname, filepath)
```
whereas for regular modules it is constructed using

```py
MANAGER.ast_from_file(filepath, modname, source=True)
```
See the get_ast method in https://github.com/PyCQA/pylint/pull/3257/files/5b24700e7bf84d1f2ae6fcd468acf5a9f6f1c458

The module docstring of astroid.manager suggests that the Manager should be used for both cases in pylint. 

Therefore, AstroidManager should provide a way to create an AST from a string.

**Comment by PCManticore** [comment]
Thanks for opening an issue @thisch ! This is a matter of exposing a new `ast_from_string` API in `AstroidManager` which can look like:
```
    def ast_from_string(self, data, modname="", path=None):
        """Build astroid from source code string."""
        from astroid.builder import AstroidBuilder

        return AstroidBuilder(self).string_build(data, modname, path=path)
```

Is this something that you'd be interested in working on?

**Comment by thisch** [comment]
Currently not. I'll wait a bit and work on it if no one else volunteers.
