### ISSUE TITLE
typed_ast on Python 3.8

### ISSUE THREAD

**Issue by The-Compiler** [PyCQA/astroid#741]
It looks like `typed_ast` 1.4.0 supports Python 3.8. However, astroid doesn't install it in that situation:

https://github.com/PyCQA/astroid/blob/67321ee2f97b5b096acee9d2395a32bb6e68083a/astroid/__pkginfo__.py#L28

I'd happily open a PR for this - would you prefer this on the `2.3` or `master` branch? If you prefer, feel free to do the change yourself, might be quicker that way.

**Comment by PCManticore** [comment]
I was under the impression that typed_ast merged into the built-in ast module on Python 3.8, isn't that the case? Do you have any issues with type comments on Python 3.8 that would have been ignored with typed_ast being installed?

**Comment by PCManticore** [comment]
Also yeah, feel free to send a PR!

**Comment by The-Compiler** [comment]
> I was under the impression that typed_ast merged into the built-in ast module on Python 3.8, isn't that the case? Do you have any issues with type comments on Python 3.8 that would have been ignored with typed_ast being installed?

Hmm, you're right, I don't! I just discovered this after re-running a script generating pinned requirements files with Python 3.8. Indeed the typed_ast readme says:

> typed_ast will not be updated to support parsing Python 3.8 and newer. Instead, it is recommended to use the stdlib ast module there, which has been augmented to support extracting type comments and has limited support for parsing older versions of Python 3.

so I'm closing this.
