### ISSUE TITLE
Exception when invoking `infer_lhs()` on `AssignAttr`

### ISSUE THREAD

**Issue by ltcmelo** [PyCQA/astroid#745]
### Steps to reproduce
I got the exception below in a large project and I don't have a concise snippet to reproduce it. Yet, I'd like to report the basics of the issue; then you can take it under consideration.

*a.py*
```python
class Configuration:
    def __init__(self):
        self.input_dir = None
```

*b.py*
```python
config = Configuration()
config.input_dir = p  # where p is a for variable
```

At some point in my code, I get the [AssignAttr](http://pylint.pycqa.org/projects/astroid/en/latest/api/astroid.nodes.html#astroid.nodes.AssignAttr) node (let's call it `n`) for `config.input_dir` and invoke `n.infer_lhs()`.

### Current behavior

I get this exception:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/astroid/inference.py", line 310, in infer_attribute
    context.boundnode = owner
AttributeError: 'NoneType' object has no attribute 'boundnode'
```

<img width="1131" alt="Screen Shot 2020-01-23 at 15 54 16" src="https://user-images.githubusercontent.com/2905588/73014262-99d0c080-3df8-11ea-8a1b-2ae4ef09da7c.png">

### Expected behavior

No exception, and the usual possible results from the `infer` function(s).

**Comment by ltcmelo** [comment]
Very succinct (possibly, incomplete) [PR for this](https://github.com/PyCQA/astroid/pull/746).

**Comment by PCManticore** [comment]
Thanks for the report! The PR seems like it might fix the issue, we just need a regression test to confirm it.
