### ISSUE TITLE
Tidelift logo is broken on PyPI

### ISSUE THREAD

**Issue by webknjaz** [PyCQA/astroid#753]
It's visible @ https://pypi.org/project/astroid/. The reason is that README uses a relative link to the image and gets embedded as is which works within GitHub but this URL doesn't work on PyPI.

Solution: use a full absolute URL, could even use https://cdn2.hubspot.net/hubfs/4008838/website/logos/logos_for_download/Tidelift_primary-shorthand-logo.png instead of embedding it into the repo.

**Comment by DanielNoord** [comment]
This seems to be working as intended now! Closing 😄
