### ISSUE TITLE
Attempting to unpack a non-sequence for numpy array shape

### ISSUE THREAD

**Issue by jvanvugt** [PyCQA/astroid#766]
### Steps to reproduce
Run PyLint on the following code:
```python
import numpy as np

def foo():
    return np.zeros(4, 5, 8)

tensor = foo()
dim1, dim2, dim3 = tensor.shape
```

Versions:  
pylint 2.4.4  
astroid 2.3.3

### Current behavior
PyLint finds error `unpacking-non-sequence`

### Expected behavior
PyLint understands that `numpy.ndarray` is a sequence.

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output
2.3.3

**Comment by hippo91** [comment]
@jvanvugt with latest `pylint` and `astroid` version, the bug doesn't occur anymore.
This is due to the commit 20ed6ed8b4571d3026941b08e64e0b73d020c5e5.
