### ISSUE TITLE
astroid triggers `DeprecationWarning`s when accessing deprecated package members

### ISSUE THREAD

**Issue by CrepeGoat** [PyCQA/astroid#770]
(I discovered this behavior when using pylint, and will describe the issue in the context of pylint.)

### Steps to reproduce
1. create a venv, activate, and install `pylint` and `wxpython`:
```
> python -m venv venv
> venv\Scripts\activate
(venv) > pip install pylint wxpython
```
2. create a dummy python script with the following content:
```python3
import wx
```
3. create a config file:
```
(venv) > python -m pylint --generate-rcfile
```
4. add `wx` to its `extension-pkg-whitelist`:
```
[MASTER]

# A comma-separated list of package or module names from where C extensions may
# be loaded. Extensions are loading into the active Python interpreter and may
# run arbitrary code.
extension-pkg-whitelist=wx
```
5. run pylint on the dummy python file, removing stdout output (here done assuming a windows platform):
```
(venv) > python -m pylint dummy.py > nul
```

### Current behavior
The last command in the above steps produces the following output (user directories renamed):
```
(venv) > python -m pylint dummy.py > nul
C:\path_to_dir\venv\lib\site-packages\astroid\raw_building.py:317: wxPyDeprecationWarning: Accessing deprecated property. Use altDown instead.
  member = getattr(obj, name)
C:\path_to_dir\venv\lib\site-packages\astroid\raw_building.py:317: wxPyDeprecationWarning: Accessing deprecated property. Use controlDown instead.
  member = getattr(obj, name)
C:\path_to_dir\venv\lib\site-packages\astroid\raw_building.py:317: wxPyDeprecationWarning: Accessing deprecated property. Use metaDown instead.
  member = getattr(obj, name)
C:\path_to_dir\venv\lib\site-packages\astroid\raw_building.py:317: wxPyDeprecationWarning: Accessing deprecated property. Use shiftDown instead.
  member = getattr(obj, name)
(venv) >
```

### Expected behavior
Personally, *I* expect the last command in the above steps to produce *no* output:
```
(venv) > python -m pylint dummy.py > nul
(venv) >
```
I say so because there were no strict "errors" that were encountered in running this program; to my point, pylint still successfully produces lints for this file (these can be shown by running the last command, omitting the "> nul" suffix). However, as I don't have an intimate knowledge of the package, I don't know whether it's good or bad practice to allow `DeprecationWarning`'s to propogate up to stderr. Please advise.

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output
2.3.3

### pylint --version output
```
pylint 2.4.4
astroid 2.3.3
Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
```

**Comment by CrepeGoat** [comment]
In my brief experimentation, I found that the following changes to "astroid/raw_building.py" averts the `DeprecationWarning`s:
```diff
24a25
> import warnings
317,318c318,321
<                 member = getattr(obj, name)
<             except AttributeError:
---
>                 with warnings.catch_warnings():
>                     warnings.filterwarnings('error')
>                     member = getattr(obj, name)
>             except (AttributeError, DeprecationWarning):
```

However, again I am not a contributor and do not know this code well. I write this hoping it shortens the investigation required by someone more knowledgeable. Maintainers please advise.

**Comment by PCManticore** [comment]
Hey @CrepeGoat Yeah, that looks like a decent solution to avoid emitting the `DeprecationWarning`, which is not something the user will be able to control anyway with `extension-pkg-whitelist`. Would you have some time to submit a patch for it?

**Comment by CrepeGoat** [comment]
Sure. If I put that through sometime this week (maybe this weekend), is that soon enough? Never contributed to an open-source project; I'll want to set aside time to read the contributing docs and get it right the first time.
