### ISSUE TITLE
Astroid 2.4.0 installs a tests package in site-packages

### ISSUE THREAD

**Issue by fbochu** [PyCQA/astroid#774]
### Steps to reproduce
1. Install astroid 2.4.0

### Current behavior

A `tests` package is installed in site-packages.

### Expected behavior

Only `astroid` package is installed in site-packages.

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output
2.4.0

**Comment by fbochu** [comment]
The following patch will fix this issue:
``` diff
diff --git a/setup.py b/setup.py
index 0e35ae78..6caf0639 100644
--- a/setup.py
+++ b/setup.py
@@ -47,7 +47,7 @@ def install():
         python_requires=">=3.5.*",
         install_requires=install_requires,
         extras_require=extras_require,
-        packages=find_packages() + ["astroid.brain"],
+        packages=find_packages(exclude=['tests']) + ["astroid.brain"],
         setup_requires=pytest_runner,
         test_suite="test",
         tests_require=["pytest"],
```

**Comment by scottfurry** [comment]
Confirming @fbochu patch. Arrived at the same solution (albeit 6h later having not read the bug report).
