### ISSUE TITLE
astroid/rebuilder.py: KeyError: <class '_ast.Is'> running pylint

### ISSUE THREAD

**Issue by raymond-grointel** [PyCQA/astroid#783]
Source: https://github.com/PyCQA/pylint/issues/3558

2.4.0 is currently broken. Fix is in master -- lets keep this open until 2.4.1 is released.

**Comment by PCManticore** [comment]
This has also been backported to 2.4.1, I see no reason why we need to keep it open.

**Comment by raymond-grointel** [comment]
2.4.1 hasn't been tagged or released https://pypi.org/project/astroid/#history

**Comment by PCManticore** [comment]
It's going to be tagged and released, just have a bit more patience. We close issue that are fixed even though the fixed have not been released, since otherwise it would require additional work on our side to double check again whenever we release the fixes.
