### ISSUE TITLE
lazy-object-proxy update to 1.5.0 breaks astroid

### ISSUE THREAD

**Issue by priv-kweihmann** [PyCQA/astroid#800]
### Steps to reproduce
1. locally install lazy-object-proxy==1.5.0
2. locally install astroid

### Current behavior
Exception
> Requirement.parse('lazy_object_proxy==1.4.*'), {'astroid'})

### Expected behavior
Works as before, as I don't see any breaking changes in lazy-object-proxy
Before e1b4e11e383bf281544f1300e41eea2ac6ab251c this would have worked

**Comment by The-Compiler** [comment]
pylint/astroid worked just fine for me with lazy-object-proxy==1.5.0 and wrapt==1.12.1 (which I pinned explicitly), so I just noticed this now. What's the point of the pinning in e1b4e11? If it's to avoid backwards incompatibilities, wouldn't just pinning to `<2` make more sense?

**Comment by priv-kweihmann** [comment]
May it would, I don't know. Maybe ping the original author?

**Comment by Callek** [comment]
@PCManticore can you please elaborate here?
