### ISSUE TITLE
dataclass_json support

### ISSUE THREAD

**Issue by MichaelMcClure** [PyCQA/astroid#810]
Add support for [dataclass_json](https://pypi.org/project/dataclasses-json/) that adds .`to_json()` and `.to_dict()` methods.

It appears the code to add dataclass support was added in 2.4 and [updated in 2.4.2](https://github.com/PyCQA/astroid/commit/3e4eac76e9abfa0400fa07b58c61973ac5495bd2).
This issue is present in Asteroid 2.4.2

Perhaps a similar change could add support for the dataclass_json decorator `@dataclass_json`.
Please note there is a workaround for this - use ["Approach 2: Inherit from a mixin"](https://pypi.org/project/dataclasses-json/)

### Steps to reproduce
1.  Create a class using dataclass and dataclass_json like so:
```
from dataclasses import dataclass
from dataclasses_json import dataclass_json

@dataclass_json
@dataclass
class Person:
    name: str
```
2. Create a unit test for that class:
```
import unittest
import os, sys
from models import Person

root_app_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.append(root_app_dir)

class TestDataModels(unittest.TestCase):
    def test_models(self):
        with open(root_app_dir + '/tests/unit/data/result-good.json') as f:
            person_result_json = f.read()
        person_result = Person.from_json(person_result_json)
        self.assertIsNotNone(person_result)
```

3. Run pylint and get "no_member" error
`python -m pylint -E --rcfile=.pylintrc && echo "--> No pylint action issues found"`
************* Module tests.integration.person.Person
tests/unit/test_data_models.py:12:31: E1101: Instance of 'Person' has no 'to_json' member (no-member)

4. Alternate Path -  no defect,  tests pass, linter does not raise errors:
Change #1 Person to:
```
from dataclasses import dataclass
from dataclasses_json import DataClassJsonMixin

@dataclass
class Person(DataClassJsonMixin):
    name: str
```

repeat #2 and #3 above with no linting failures.

### Current behavior
3. Run pylint and get "no_member" error
`python -m pylint -E --rcfile=.pylintrc && echo "--> No pylint action issues found"`
************* Module tests.integration.person.Person
tests/unit/test_data_models.py:12:31: E1101: Instance of 'Person' has no 'to_json' member (no-member)

### Expected behavior
3. Run pylint and get "no_member" error
`python -m pylint -E --rcfile=.pylintrc && echo "--> No pylint action issues found"`
--> No pylint action issues found

**Comment by PCManticore** [comment]
Hi @MichaelMcClure Thanks for the report. Unfortunately we are not able to follow up with transforms for all the packages and we're mostly intending to implement transforms for popular ones. In this case you have multiple options:

1. Write a transform yourself (basically a pylint plugin) and use it with `pylint`
2. Use `--generated-members` option
3. Use `--ignored-classes`
4. Or even `--ignored-modules`
