### ISSUE TITLE
[brain] Numpy ufunc-s can work with non-ndarray arguments

### ISSUE THREAD

**Issue by eugene57** [PyCQA/astroid#818]
### Steps to reproduce
Lint following file:
```
import numpy as np
import xarray as xr

x = xr.DataArray([1, -1], dims=('x',), coords={'x': ['a', 'b']})
y = np.maximum(x, 0.)
print(y.loc['b'])
```

### Current behavior
```
************* Module test_numpy
test_numpy.py:6:6: E1101: Instance of 'ndarray' has no 'loc' member (no-member)
```

Current version of astroid brain uses `FakeUfunc` subclasses returning `numpy.ndarray` explicitly. E.g. see https://github.com/PyCQA/astroid/blob/master/astroid/brain/brain_numpy_core_umath.py#L61

However, any object supporting array function protocol can be used together with numpy ufuncs.

`FakeUfuncOneArg` and `FakeUfuncOneArgBis` could be changed to return `x` instead of `numpy.ndarray([0, 0])`. But I'm not sure what to do with `FakeUfuncTwoArgs`.

### Expected behavior
No error.

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output
2.4.1

**Comment by hippo91** [comment]
@eugene57 thanks for this report.
The problem with replacing `numpy.ndarray([0, 0])` with `x` in the return value of `FakeUfuncOneArg` is that `x` type can be everything. Thus it may lead to false negative (i.e no message emitted when it should). For example:
```
a = 'foo'
y = np.maximum(a, 0.)
```
would not raise any message. Thus i'm closing this issue but do not hesitate to reopen it if i'am wrong.

**Comment by eugene57** [comment]
@hippo91 
But there is still a problem with existing implementation, isn't it? Code in the description is valid but pylint reports an error. 
I do not insist on changing `FakeUfunc` implementation though.

**Comment by eugene57** [comment]
I have no access to reopen this issue...

**Comment by hippo91** [comment]
@eugene57 i reopen the issue.
