### ISSUE TITLE
AttributeError: 'Starred' object has no attribute 'name'

### ISSUE THREAD

**Issue by mristin** [PyCQA/astroid#835]
The parsing of the following file:
```
"""Module for ContentType class."""

from enum import Enum


class ContentType(Enum):
    """Enumerable to represent different `telereddit.models.post.Post` types."""

    TEXT, PHOTO, VIDEO, GIF, YOUTUBE, *_ = range(20)
```

 causes the error `AttributeError: 'Starred' object has no attribute 'name'` in `brain\brain_namedtuple_enum.py`, line 350, in `infer_enum_class`.

The version 2.4.2 of astroid was used. Perhaps somehow related to #36 ?

**Comment by PCManticore** [comment]
Thanks for the report, this will be fixed by #870
