### ISSUE TITLE
Lazy-Object-Proxy Dependency Check Fails in Offline Install

### ISSUE THREAD

**Issue by CoryBoehm** [PyCQA/astroid#840]
### Steps to reproduce
1.  Download astroid-2.4.2-py3-none-any.whl
2. Have internet access turned off/network disconnected to mirror installation to an isolated computer.
2.  Have Lazy-Object-Proxy, Six and Wrapt previously installed.
3.  pip list to verify the modules are present.
4.  pip install ./astroid-2.4.2-py3-none-any.whl

### Current behavior
Returns the following warning:
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000002207ACE6100>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/lazy-object-proxy

### Expected behavior
Existing installation of laxy-object-proxy should be detected removing attempt to download for pypi.org Installation should then complete without issue.

**Comment by PCManticore** [comment]
Thanks for the report. It's possible that the lazy-object-proxy version you are using is not the one that astroid wants to use. I think we need more details on what versions you were using here but I don't think it's an actual problem with astroid.
