### ISSUE TITLE
Incorrect MRO inferred with multiple inheritance from module-qualified classes

### ISSUE THREAD

**Issue by timmartin** [PyCQA/astroid#843]
### Steps to reproduce

File `other.py`:

    class A:
        pass

    class B:
        pass

Then run:

    import astroid

    class_node = astroid.extract_node("""
    import other

    class Child(other.A, other.B): #@
        pass
    """)

    print([cls.name for cls.name in class_node.mro()])

### Current behavior

    ['Child', 'A', 'object']

### Expected behavior

    ['Child', 'A', 'B', 'object']

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output

2.5.0

**Comment by timmartin** [comment]
I believe [this change](https://github.com/timmartin/astroid/commit/ffa6bcb757797c3ab2aebd8b9f29018a7022d9ea) will fix this, I just need to write a proper PR.

I think the problem is that when we run multiple inferences in `_inferred_bases`, the context is reused which means the second and subsequent inferences have bad data. Cloning the context before running the inference seems to address this.

**Comment by hippo91** [comment]
@timmartin thanks for the report. I can reproduce it.
One interesting thing is:
```
import astroid

class_node = astroid.extract_node("""
from other import A, B

class Child(A, B): #@
    pass
""")

print([cls.name for cls in class_node.mro()])
```
prints: `['Child', 'A', 'B', 'object']`

**Comment by timmartin** [comment]
Yes, that's correct. I believe this is because in the first case, there is non-trivial inference that must be applied to each expression (`other.A`, `other.B`) to determine its type, and sharing the context between the two `infer` calls causes the second to fail. In the second case, the shared context doesn't affect the second `infer` call, either because the two expressions are so trivial or because there's no overlap between the names in the two expressions. I'm mostly guessing this from context, I don't yet properly understand how the inference works.
