### ISSUE TITLE
Compare node inferring 

### ISSUE THREAD

**Issue by usagitoneko97** [PyCQA/astroid#846]
This might be obvious, but I can't find any issue on compare node inferring. I maybe wrong here. but I thought that it will be a straight forward implementation, similar to `binop` implementation. Perhaps because of multiple comparators complicate things?

### Steps to reproduce
from astroid.builder import parse
module = parse(
    """
    x = 1 > 2
    """
)
inferred = next(module["x"].infer())
print(inferred)

### Current behavior
Uninferable

### Expected behavior
`False` const

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output
2.5.0

**Comment by hippo91** [comment]
@usagitoneko97 it is indeed surprising. Maybe @PCManticore or @AWhetter will have an answer?
