### ISSUE TITLE
lazy-object-proxy 1.5.1 is not supported

### ISSUE THREAD

**Issue by HilitOreny** [PyCQA/astroid#848]
### Steps to reproduce
1. I have Astroid version 2.4.2 installed. I use Python 3.9 on Windows 10. 

2. Open pip and look for outdated packages. You will find that the installed version of lazy-object-proxy is 1.4.3 but the latest version is 1.5.1.

![image](https://user-images.githubusercontent.com/69712717/97259681-0cf1e200-1824-11eb-8136-1d29fffb7252.png)

3. Update lazy-object-proxy.

![image](https://user-images.githubusercontent.com/69712717/97260110-f5672900-1824-11eb-8a40-d5050aae293b.png)

### Current behavior

Astroid 2.4.2 requires lazy-object-proxy==1.4.*, but you'll have lazy-object-proxy 1.5.1 which is incompatible.

![image](https://user-images.githubusercontent.com/69712717/97260179-1760ab80-1825-11eb-8464-6f0387a0e265.png)

### Expected behavior

Please support  lazy-object-proxy 1.5.1.

**Comment by hippo91** [comment]
@HilitOreny thanks for your report.

**Comment by PCManticore** [comment]
The current version from the `master` branch supports an updated version of lazy-object-proxy. This will be fixed once we release the new version.

**Comment by surkova** [comment]
@PCManticore Hi! When is the release expected? What should we do in the meanwhile before the new version is pushed?

**Comment by hippo91** [comment]
@surkova we will try to make the release ASAP. If you want to already have the new functionalities i think the best way is to use master branches of `astroid` and `pylint`.

**Comment by surkova** [comment]
@hippo91 my main concern is incorrect definition of dependencies. For now we locked the version of `lazy-object-proxy` to `1.4.3` so that it works with `astroid`.
