### ISSUE TITLE
calling `parent` on a node that is part of a type comment returns the (original) `_ast` module's FunctionDef

### ISSUE THREAD

**Issue by ltcmelo** [PyCQA/astroid#851]
Consider this snippet:

```python
def f(s):
    # type: (str) -> int
    return 42
```

Given the `node` from the type comment, `Name.int(name='int')`, if I call its parent (i.e., `node.parent`), I get the original _ast module's FunctionDef, instead of astroid's FunctionDef.

**Comment by PCManticore** [comment]
Hi, thanks for the report. I tried to reproduce this but I was not able, can you paste the exact code you used to demonstrate the issue?

**Comment by ltcmelo** [comment]
@PCManticore, reproducibility of this one is straightforward to me, here's a (partial) example — but note that I had a typo in the original snippet: I missed the colon after `type`, which I just fixed; perhaps this is the reason you couldn't reproduce?

Assume an AST visitor with:

```
def visit_functiondef(self, node: nodes.FunctionDef)
   print(f'the parent of type comment return is {node.type_comment_returns.parent}')
```

To me, this prints:
<img width="565" alt="Screen Shot 2021-01-04 at 12 06 04" src="https://user-images.githubusercontent.com/2905588/103548904-3a42b800-4e85-11eb-8bca-aa2f9a17313f.png">

**Comment by AWhetter** [comment]
I've just hit this myself. Here's what I did to reproduce:

```python
>>> import astroid
>>> f = astroid.extract_node("""
def f(a):
    # type: (A) -> None
    pass
""")
>>> f.type_comment_args[0].parent
<ast.FunctionDef object at 0x7f0b0fb077f0>
```

**Comment by PCManticore** [comment]
Thanks @AWhetter and @ltcmelo
