### ISSUE TITLE
Infer does not shows multiple values for assignments inside while loop

### ISSUE THREAD

**Issue by orSolocate** [PyCQA/astroid#853]
I have noticed that although the `infer` process succeeds to grasp two separate values from `if` block, it does not work for while block.

### Steps to reproduce

```
module = astroid.parse(
    """
   A=1            
   while A<5:
       if A>2:
           pass
       A=A+1
    """)
list(next(next(module.body[1].body[0].get_children()).get_children()).infer())
```

### Current behavior
returns:
`[<Const.int l.2 at 0x1878165ac48>]
`which value is A=1 only

### Expected behavior
All possibilities for A, i,e:  A=1,2,3,4
`[<Const.int l.2 at 0x1878165ac48>.<Const.int l.2 at ?>,<Const.int l.2 at ?>,<Const.int l.2 at ?>]
`

Demonstration of how it works well with `if` block:

```
module = astroid.parse(
    """
    # Scenario 58
   B=foo()
   if B>5:
       A=2
   else:
       A=6
   if A<4:
       pass
    """)
list(next(next(module.body[-1].get_children()).get_children()).infer())
```

returns:
`[<Const.int l.5 at 0x18781651208>, <Const.int l.7 at 0x187816b94c8>]
`which corresponds to A=2 and A=6, as you expect from the infer algorithm.

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output
2.5.0

**Comment by PCManticore** [comment]
Thanks for the report. I don't think we will be able to follow up with this, since astroid's inference is rather dumb and it won't be trivial to interpret all the possible states a variable can take during a loop.
