### ISSUE TITLE
Support for wrapt 1.12.1

### ISSUE THREAD

**Issue by FelixMoelder** [PyCQA/astroid#859]
### Steps to reproduce
1. Execute `conda build` on the conda-forge `astroid-feedstock` on a Apple Silicon device.

### Current behavior
Building fails with the following message: `conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-arm64: {'wrapt=1.11' ,'lazy-object-proxy=1.4'}`
This occurs as only wrapt>=1.12.1 is build for `osx_arm64`.

### Expected behavior

Please add support for wrapt 1.12.1

**Comment by PCManticore** [comment]
The PR has been merged.
