### ISSUE TITLE
Please bump dependency version of six

### ISSUE THREAD

**Issue by dgilmanTORQATA** [PyCQA/astroid#863]
The current 1.12 dependency is two years old, and there are some other packages out in the Python ecosystem that are starting to depend on newer versions of six. For us, this was google-api-core and related Google cloud packages, but as time goes on that will only increase.

Alternatively, your package now is python 3 only. It would be good to drop the dependency entirely.

**Comment by AWhetter** [comment]
This has already been fixed since astroid 2.4.0 (https://github.com/PyCQA/astroid/commit/4a244535ecb5530a1c346f8bd39800f3282f3396).
