### ISSUE TITLE
Make lazy-object-proxy compatible with 1.5.2 or latest version

### ISSUE THREAD

**Issue by machinexa2** [PyCQA/astroid#888]
Make lazy-object-proxy compatible with 1.5.2 or latest version

**Comment by PCManticore** [comment]
Hey @machinexa2 I'm not fully sure what this request is about. We're using the `1.4.2+` version for `lazy-object-proxy` over [here](https://github.com/PyCQA/astroid/blob/master/astroid/__pkginfo__.py#L31).
