### ISSUE TITLE
The license text at https://github.com/PyCQA/astroid/blob/master/COPYING is wrong

### ISSUE THREAD

**Issue by ashahba** [PyCQA/astroid#891]
While working on putting some third party programs list I noticed that the actual text for the license file in the repo is `GPLv2` because it's pointing to `COPYING` file. But there is also the file `COPYING.LESSER` which is the right license for the repo.

My thinking is after `10` years it's safe to replace the old old irrelevant `COPYING` file with `COPYING.LESSER` while fixing the links across the board to point to the new file.

This is less confusing for the users like me who actually read through the licence text to ensure they are what they are supposed to 🙂

**Comment by hippo91** [comment]
@ashahba thanks for the report. @Pierre-Sassoulas @AWhetter what do you think about it?

**Comment by Pierre-Sassoulas** [comment]
I don't have an opinion on this I know too little about pylint's license. @PCManticore are you okay with changing this ?

**Comment by AWhetter** [comment]
I would prefer to wait for @PCManticore's guidance as well, but I think we're supposed to be using LGPL v2.1 so we could `mv COPYING.lesser COPYING` to remove COPYING.lesser and have COPYING contain the correct text.

**Comment by cdce8p** [comment]
From what I can tell, `LGPL v2.1` is indeed the correct version. https://github.com/PyCQA/astroid/commits/master/COPYING
It started with `GPL` in 2006 and was fully replaced with `LGPL` in 2010 but somehow the `GPL` license file survived. All file headers indicate `LGPL` though.
