### ISSUE TITLE
False positive for not-an-iterable in astroid 2.5

### ISSUE THREAD

**Issue by tschaub** [PyCQA/astroid#896]
### Steps to reproduce

`test.py`

```py
from schematics.models import Model
from schematics.types import ListType, StringType

class Store(Model):
    foods = ListType(StringType)

def test_pylint():
    store = Store({"foods": ["chicken", "soup"]})
    for food in store.foods:
        print(food)

if __name__ == "__main__":
    test_pylint()
```

```
pylint test.py --errors-only
```

### Current behavior

```
************* Module test
test.py:9:16: E1133: Non-iterable value store.foods is used in an iterating context (not-an-iterable)
```

### Expected behavior

No errors.  This was the behavior at 2.4.2.

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output

```
2.5
```

Also, from `pylint --version`
```
pylint 2.6.0
astroid 2.5
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
```

**Comment by hippo91** [comment]
@tschaub thanks for your report.
I can reproduce it. However i can reproduce it even with `astroid 2.4.2` (even `2.4.1`):
```
************* Module bug_pylint_896
bug_pylint_896.py:1:0: C0114: Missing module docstring (missing-module-docstring)
bug_pylint_896.py:4:0: C0115: Missing class docstring (missing-class-docstring)
bug_pylint_896.py:7:0: C0116: Missing function or method docstring (missing-function-docstring)
bug_pylint_896.py:9:16: E1133: Non-iterable value store.foods is used in an iterating context (not-an-iterable)

------------------------------------------------------------------
Your code has been rated at 2.00/10 (previous run: 2.00/10, +0.00)
```
```
pylint --version
pylint 2.6.0
astroid 2.4.2
Python 3.9.0 (default, Nov 26 2020, 08:37:08) 
[GCC 8.3.0]
```

What is the version of `schematics` do you use?

**Comment by hippo91** [comment]
I check with `schematics==1.1.3` and there is no false positive. 
However starting from 2.0 the false positive appears.

**Comment by tschaub** [comment]
We're using `schematics==2.1.0`.  I also see the same issue with `astroid==2.4.2` with the simplified `test.py` above.

In the case where this came up, the false positive occurs with `astroid==2.5.0` but not with `astroid==2.4.2`.  The actual use case is more complicated than the `test.py` above.  I guess `astroid` is able to dig deeper now.

**Comment by hippo91** [comment]
@tschaub is it possible to have the actual use case or something close?

**Comment by tschaub** [comment]
@hippo91 - I've tried to come up with a minimal test case that works with 2.4.2 and not 2.5.0, but haven't succeeded yet.  Our actual use case uses a private package that depends on schematics.  I'm still trying to strip it down into something others could reproduce.

**Comment by hippo91** [comment]
Ok. Thanks @tschaub

**Comment by hippo91** [comment]
@tschaub i'm trying to investigate this bug a little bit and i'am a bit confused.
I cannot find a set of versions of `pylint`/`astroid`/`schematics` with which the problem does not arise.
I think it has always been there. Can you confirm?

**Comment by tschaub** [comment]
I'm no longer working on the project where this was an issue.  Maybe worth closing if there isn't a clear path to a fix.

**Comment by hippo91** [comment]
@tschaub thanks for your answer. I will close this issue. If anyone is facing the same problem again, then i will reopen it.
