### ISSUE TITLE
False positive with Enum.__members__.items()

### ISSUE THREAD

**Issue by chiefnoah** [PyCQA/astroid#899]
### Steps to reproduce
1. Use an enum's `__members__` field:
```python

from enum import Enum

class TestEnum(Enum):
    ONE = 1
    TWO = 2

print(x for x in TestEnum.__members__.items())
```
2. Run pylint with astroid 2.5 installed
```shell
$ pylint --version
pylint 2.6.2
astroid 2.5
Python 3.8.7 (default, Dec 26 2020, 08:45:55)
[GCC 10.2.1 20201203]
``` 

### Current behavior

$ pylint test.py
************* Module test
test.py:1:0: C0114: Missing module docstring (missing-module-docstring)
test.py:3:0: C0115: Missing class docstring (missing-class-docstring)
test.py:7:17: E1101: Function '__members__' has no 'items' member (no-member)

--------------------------------------------------------------------
Your code has been rated at -4.00/10 (previous run: -4.00/10, +0.00)

### Expected behavior

Not complaining about `__members__.items()`

### ``python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"`` output

2.5

See #895

**Comment by hippo91** [comment]
@chiefnoah thanks for this report and the reproducer.
I can reproduce it.
The faulty commit is the same as the one of #895 (cc3bfc5dc94062a582b7b3226598f09d7ec7044e).
I'm looking for a fix.

**Comment by hippo91** [comment]
@chiefnoah i reverted the faulty commit in #901. I am the author of this commit. It was a try to improve the inference of `numpy` objects.
Apologies for the regression you faced.
