### ISSUE TITLE
Unexpected behavior with FunctionDef.decoratornames()

### ISSUE THREAD

**Issue by tiagohonorato** [PyCQA/astroid#917]
### Steps to reproduce
Run the following with Python 3.7 and Python 3.8:

```
import astroid

node = astroid.extract_node(
    """
import functools
class Test():
    @property
    def test_property(self):
        return 5

class Child(Test):
    @functools.cached_property
    def test_property(self): #@
        return super().test_property + 5
"""
)

print(node.decoratornames())

```

### Current behavior

On Python 3.8, it returns ``{'functools.cached_property'}``
On Python 3.7, it returns ``set()``

Apparently, ``NodeNG.infer()`` raises ``InferenceError``when iterating the results in Python 3.7, but not in Python 3.8 when running the same code.

### Expected behavior

Return ``{'functools.cached_property'}`` on Python 3.7

### Astroid version

Tested with ``2.5`` and ``2.4.2``

**Comment by hippo91** [comment]
@tiagohonorato thanks for the report!
