### ISSUE TITLE
`as_string` function returns identical strings for different nodes

### ISSUE THREAD

**Issue by friyaz** [PyCQA/astroid#996]
### Steps to reproduce
```python
import astroid

snip_1 = """
info += f' {v:.4f}'
"""

snip_2 = """
info += f' {v:.4e}'
"""

parsed_snip1 = astroid.parse(snip_1)
parsed_snip2 = astroid.parse(snip_2)

print(parsed_snip1.as_string() == parsed_snip2.as_string())

print(parsed_snip1.as_string())
print(parsed_snip2.as_string())
```

### Current behavior
```
True
info += f' {v}'


info += f' {v}'
```
### Expected behavior
```
False
info += f' {v: 4f}'


info += f' {v: 4e}'
```
### `python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"` output
2.3.3

**Comment by hippo91** [comment]
@friyaz thanks for the report. It is indeed quite strange.

**Comment by faisal-deepsource** [comment]
@hippo91 this is working correctly on the master branch. I just checked it.

**Comment by friyaz** [comment]
@hippo91 this is working correctly on the master branch. I just checked it.

**Comment by hippo91** [comment]
@friyaz thanks for the update. I close this issue as it seems to be already fixed in master.
